CodeMirror.defineMode("javascript",function(R,r){function F(a,d){for(var c=!1,b;null!=(b=a.next());){if(b==d&&!c)return!1;c=!c&&"\\"==b}return c}function m(a,d,c){t=a;G=c;return d}function u(a,d){var c=a.next();if('"'==c||"'"==c)return c=S(c),d.tokenize=c,c(a,d);if(/[\[\]{}\(\),;\:\.]/.test(c))return m(c);if("0"==c&&a.eat(/x/i))return a.eatWhile(/[\da-f]/i),m("number","number");if(/\d/.test(c)||"-"==c&&a.eat(/\d/))return a.match(/^\d*(?:\.\d*)?(?:[eE][+\-]?\d+)?/),m("number","number");if("/"==c){if(a.eat("*"))return c=
H,d.tokenize=c,c(a,d);if(a.eat("/"))return a.skipToEnd(),m("comment","comment");if("operator"==d.lastType||"keyword c"==d.lastType||/^[\[{}\(,;:]$/.test(d.lastType))return F(a,"/"),a.eatWhile(/[gimy]/),m("regexp","string-2");a.eatWhile(y);return m("operator",null,a.current())}if("#"==c)return a.skipToEnd(),m("error","error");if(y.test(c))return a.eatWhile(y),m("operator",null,a.current());a.eatWhile(/[\w\$_]/);var c=a.current(),b=I.propertyIsEnumerable(c)&&I[c];return b&&"."!=d.lastType?m(b.type,
b.style,c):m("variable","variable",c)}function S(a){return function(d,c){F(d,a)||(c.tokenize=u);return m("string","string")}}function H(a,d){for(var c=!1,b;b=a.next();){if("/"==b&&c){d.tokenize=u;break}c="*"==b}return m("comment","comment")}function z(a,b,c,e,f,g){this.indented=a;this.column=b;this.type=c;this.prev=f;this.info=g;null!=e&&(this.align=e)}function n(){for(var a=arguments.length-1;0<=a;a--)f.cc.push(arguments[a])}function b(){n.apply(null,arguments);return!0}function A(a){function b(c){for(;c;c=
c.next)if(c.name==a)return!0;return!1}var c=f.state;c.context?(f.marked="def",b(c.localVars)||(c.localVars={name:a,next:c.localVars})):b(c.globalVars)||(c.globalVars={name:a,next:c.globalVars})}function J(){f.state.context={prev:f.state.context,vars:f.state.localVars};f.state.localVars=T}function K(){f.state.localVars=f.state.context.vars;f.state.context=f.state.context.prev}function k(a,b){var c=function(){var c=f.state;c.lexical=new z(c.indented,f.stream.column(),a,null,c.lexical,b)};c.lex=!0;return c}
function h(){var a=f.state;a.lexical.prev&&(")"==a.lexical.type&&(a.indented=a.lexical.indented),a.lexical=a.lexical.prev)}function l(a){return function(d){return d==a?b():";"==a?n():b(arguments.callee)}}function p(a){return"var"==a?b(k("vardef"),B,l(";"),h):"keyword a"==a?b(k("form"),g,p,h):"keyword b"==a?b(k("form"),p,h):"{"==a?b(k("}"),C,h):";"==a?b():"if"==a?b(k("form"),g,p,h,U(f.state.indented)):"function"==a?b(v):"for"==a?b(k("form"),l("("),k(")"),V,l(")"),h,p,h):"variable"==a?b(k("stat"),W):
"switch"==a?b(k("form"),g,k("}","switch"),l("{"),C,h,h):"case"==a?b(g,l(":")):"default"==a?b(l(":")):"catch"==a?b(k("form"),J,l("("),L,l(")"),p,h,K):n(k("stat"),g,l(";"),h)}function g(a){return M.hasOwnProperty(a)?b(q):"function"==a?b(v):"keyword c"==a?b(N):"("==a?b(k(")"),N,l(")"),h,q):"operator"==a?b(g):"["==a?b(k("]"),w(g,"]"),h,q):"{"==a?b(k("}"),w(X,"}"),h,q):b()}function N(a){return a.match(/[;\}\)\],]/)?n():n(g)}function q(a,d){if("operator"==a)return/\+\+|--/.test(d)?b(q):"?"==d?b(g,l(":"),
g):b(g);if(";"!=a){if("("==a)return b(k(")"),w(g,")"),h,q);if("."==a)return b(Y,q);if("["==a)return b(k("]"),g,l("]"),h,q)}}function W(a){return":"==a?b(h,p):n(q,l(";"),h)}function Y(a){if("variable"==a)return f.marked="property",b()}function X(a,d){if("variable"==a){if(f.marked="property","get"==d||"set"==d)return b(Z)}else if("number"==a||"string"==a)f.marked=a+" property";if(M.hasOwnProperty(a))return b(l(":"),g)}function Z(a){if(":"==a)return b(g);if("variable"!=a)return b(l(":"),g);f.marked=
"property";return b(v)}function w(a,d){function c(e){return","==e?b(a,c):e==d?b():b(l(d))}return function(e){return e==d?b():n(a,c)}}function C(a){return"}"==a?b():n(p,C)}function O(a){return":"==a?b($):n()}function $(a){return"variable"==a?(f.marked="variable-3",b()):n()}function B(a,d){return"variable"==a?(A(d),D?b(O,E):b(E)):n()}function E(a,d){if("="==d)return b(g,E);if(","==a)return b(B)}function U(a){return function(d,c){return"keyword b"==d&&"else"==c?(f.state.lexical=new z(a,0,"form",null,
f.state.lexical),b(p,h)):n()}}function V(a){return"var"==a?b(B,l(";"),x):";"==a?b(x):"variable"==a?b(aa):b(x)}function aa(a,d){return"in"==d?b(g):b(q,x)}function x(a,d){return";"==a?b(P):"in"==d?b(g):b(g,l(";"),P)}function P(a){")"!=a&&b(g)}function v(a,d){if("variable"==a)return A(d),b(v);if("("==a)return b(k(")"),J,w(L,")"),h,p,K)}function L(a,d){if("variable"==a)return A(d),D?b(O):b()}var s=R.indentUnit,Q=r.json,D=r.typescript,I=function(){function a(a){return{type:a,style:"keyword"}}var b=a("keyword a"),
c=a("keyword b"),e=a("keyword c"),f=a("operator"),g={type:"atom",style:"atom"},b={"if":a("if"),"while":b,"with":b,"else":c,"do":c,"try":c,"finally":c,"return":e,"break":e,"continue":e,"new":e,"delete":e,"throw":e,"var":a("var"),"const":a("var"),let:a("var"),"function":a("function"),"catch":a("catch"),"for":a("for"),"switch":a("switch"),"case":a("case"),"default":a("default"),"in":f,"typeof":f,"instanceof":f,"true":g,"false":g,"null":g,undefined:g,NaN:g,Infinity:g,"this":a("this")};if(D){var c={type:"variable",
style:"variable-3"},c={"interface":a("interface"),"class":a("class"),"extends":a("extends"),constructor:a("constructor"),"public":a("public"),"private":a("private"),"protected":a("protected"),"static":a("static"),"super":a("super"),string:c,number:c,bool:c,any:c},h;for(h in c)b[h]=c[h]}return b}(),y=/[+\-*&%=<>!?|~^]/,t,G,M={atom:!0,number:!0,variable:!0,string:!0,regexp:!0,"this":!0},f={state:null,column:null,marked:null,cc:null},T={name:"this",next:{name:"arguments"}};h.lex=!0;return{startState:function(a){return{tokenize:u,
lastType:null,cc:[],lexical:new z((a||0)-s,0,"block",!1),localVars:r.localVars,globalVars:r.globalVars,context:r.localVars&&{vars:r.localVars},indented:0}},token:function(a,b){a.sol()&&(b.lexical.hasOwnProperty("align")||(b.lexical.align=!1),b.indented=a.indentation());if(a.eatSpace())return null;var c=b.tokenize(a,b);if("comment"==t)return c;b.lastType=t;a:{var e=t,h=G,k=b.cc;f.state=b;f.stream=a;f.marked=null;f.cc=k;b.lexical.hasOwnProperty("align")||(b.lexical.align=!0);for(;;)if((k.length?k.pop():
Q?g:p)(e,h)){for(;k.length&&k[k.length-1].lex;)k.pop()();if(f.marked){c=f.marked;break a}if(e="variable"==e)b:{for(e=b.localVars;e;e=e.next)if(e.name==h){e=!0;break b}e=void 0}if(e){c="variable-2";break a}break a}c=void 0}return c},indent:function(a,b){if(a.tokenize==H)return CodeMirror.Pass;if(a.tokenize!=u)return 0;var c=b&&b.charAt(0),e=a.lexical;"stat"==e.type&&"}"==c&&(e=e.prev);var f=e.type,g=c==f;return"vardef"==f?e.indented+("operator"==a.lastType||","==a.lastType?4:0):"form"==f&&"{"==c?e.indented:
"form"==f?e.indented+s:"stat"==f?e.indented+("operator"==a.lastType||","==a.lastType?s:0):"switch"!=e.info||g?e.align?e.column+(g?0:1):e.indented+(g?0:s):e.indented+(/^(?:case|default)\b/.test(b)?s:2*s)},electricChars:":{}",jsonMode:Q}});CodeMirror.defineMIME("text/javascript","javascript");CodeMirror.defineMIME("text/ecmascript","javascript");CodeMirror.defineMIME("application/javascript","javascript");CodeMirror.defineMIME("application/ecmascript","javascript");
CodeMirror.defineMIME("application/json",{name:"javascript",json:!0});CodeMirror.defineMIME("text/typescript",{name:"javascript",typescript:!0});CodeMirror.defineMIME("application/typescript",{name:"javascript",typescript:!0});
