(function(){var S=[{keys:["Left"],type:"keyToKey",toKeys:["h"]},{keys:["Right"],type:"keyToKey",toKeys:["l"]},{keys:["Up"],type:"keyToKey",toKeys:["k"]},{keys:["Down"],type:"keyToKey",toKeys:["j"]},{keys:["Space"],type:"keyToKey",toKeys:["l"]},{keys:["Backspace"],type:"keyToKey",toKeys:["h"]},{keys:["Ctrl-Space"],type:"keyToKey",toKeys:["W"]},{keys:["Ctrl-Backspace"],type:"keyToKey",toKeys:["B"]},{keys:["Shift-Space"],type:"keyToKey",toKeys:["w"]},{keys:["Shift-Backspace"],type:"keyToKey",toKeys:["b"]},
{keys:["Ctrl-n"],type:"keyToKey",toKeys:["j"]},{keys:["Ctrl-p"],type:"keyToKey",toKeys:["k"]},{keys:["Ctrl-["],type:"keyToKey",toKeys:["Esc"]},{keys:["Ctrl-c"],type:"keyToKey",toKeys:["Esc"]},{keys:["s"],type:"keyToKey",toKeys:["c","l"]},{keys:["S"],type:"keyToKey",toKeys:["c","c"]},{keys:["Home"],type:"keyToKey",toKeys:["0"]},{keys:["End"],type:"keyToKey",toKeys:["$"]},{keys:["PageUp"],type:"keyToKey",toKeys:["Ctrl-b"]},{keys:["PageDown"],type:"keyToKey",toKeys:["Ctrl-f"]},{keys:["h"],type:"motion",
motion:"moveByCharacters",motionArgs:{forward:!1}},{keys:["l"],type:"motion",motion:"moveByCharacters",motionArgs:{forward:!0}},{keys:["j"],type:"motion",motion:"moveByLines",motionArgs:{forward:!0,linewise:!0}},{keys:["k"],type:"motion",motion:"moveByLines",motionArgs:{forward:!1,linewise:!0}},{keys:["g","j"],type:"motion",motion:"moveByDisplayLines",motionArgs:{forward:!0}},{keys:["g","k"],type:"motion",motion:"moveByDisplayLines",motionArgs:{forward:!1}},{keys:["w"],type:"motion",motion:"moveByWords",
motionArgs:{forward:!0,wordEnd:!1}},{keys:["W"],type:"motion",motion:"moveByWords",motionArgs:{forward:!0,wordEnd:!1,bigWord:!0}},{keys:["e"],type:"motion",motion:"moveByWords",motionArgs:{forward:!0,wordEnd:!0,inclusive:!0}},{keys:["E"],type:"motion",motion:"moveByWords",motionArgs:{forward:!0,wordEnd:!0,bigWord:!0,inclusive:!0}},{keys:["b"],type:"motion",motion:"moveByWords",motionArgs:{forward:!1,wordEnd:!1}},{keys:["B"],type:"motion",motion:"moveByWords",motionArgs:{forward:!1,wordEnd:!1,bigWord:!0}},
{keys:["g","e"],type:"motion",motion:"moveByWords",motionArgs:{forward:!1,wordEnd:!0,inclusive:!0}},{keys:["g","E"],type:"motion",motion:"moveByWords",motionArgs:{forward:!1,wordEnd:!0,bigWord:!0,inclusive:!0}},{keys:["{"],type:"motion",motion:"moveByParagraph",motionArgs:{forward:!1}},{keys:["}"],type:"motion",motion:"moveByParagraph",motionArgs:{forward:!0}},{keys:["Ctrl-f"],type:"motion",motion:"moveByPage",motionArgs:{forward:!0}},{keys:["Ctrl-b"],type:"motion",motion:"moveByPage",motionArgs:{forward:!1}},
{keys:["g","g"],type:"motion",motion:"moveToLineOrEdgeOfDocument",motionArgs:{forward:!1,explicitRepeat:!0,linewise:!0}},{keys:["G"],type:"motion",motion:"moveToLineOrEdgeOfDocument",motionArgs:{forward:!0,explicitRepeat:!0,linewise:!0}},{keys:["0"],type:"motion",motion:"moveToStartOfLine"},{keys:["^"],type:"motion",motion:"moveToFirstNonWhiteSpaceCharacter"},{keys:["+"],type:"motion",motion:"moveByLines",motionArgs:{forward:!0,toFirstChar:!0}},{keys:["-"],type:"motion",motion:"moveByLines",motionArgs:{forward:!1,
toFirstChar:!0}},{keys:["_"],type:"motion",motion:"moveByLines",motionArgs:{forward:!0,toFirstChar:!0,repeatOffset:-1}},{keys:["$"],type:"motion",motion:"moveToEol",motionArgs:{inclusive:!0}},{keys:["%"],type:"motion",motion:"moveToMatchedSymbol",motionArgs:{inclusive:!0}},{keys:["f","character"],type:"motion",motion:"moveToCharacter",motionArgs:{forward:!0,inclusive:!0}},{keys:["F","character"],type:"motion",motion:"moveToCharacter",motionArgs:{forward:!1}},{keys:["t","character"],type:"motion",
motion:"moveTillCharacter",motionArgs:{forward:!0,inclusive:!0}},{keys:["T","character"],type:"motion",motion:"moveTillCharacter",motionArgs:{forward:!1}},{keys:["'","character"],type:"motion",motion:"goToMark"},{keys:["`","character"],type:"motion",motion:"goToMark"},{keys:["]","`"],type:"motion",motion:"jumpToMark",motionArgs:{forward:!0}},{keys:["[","`"],type:"motion",motion:"jumpToMark",motionArgs:{forward:!1}},{keys:["]","'"],type:"motion",motion:"jumpToMark",motionArgs:{forward:!0,linewise:!0}},
{keys:["[","'"],type:"motion",motion:"jumpToMark",motionArgs:{forward:!1,linewise:!0}},{keys:["|"],type:"motion",motion:"moveToColumn",motionArgs:{}},{keys:["d"],type:"operator",operator:"delete"},{keys:["y"],type:"operator",operator:"yank"},{keys:["c"],type:"operator",operator:"change",operatorArgs:{enterInsertMode:!0}},{keys:[">"],type:"operator",operator:"indent",operatorArgs:{indentRight:!0}},{keys:["<"],type:"operator",operator:"indent",operatorArgs:{indentRight:!1}},{keys:["g","~"],type:"operator",
operator:"swapcase"},{keys:["n"],type:"motion",motion:"findNext",motionArgs:{forward:!0}},{keys:["N"],type:"motion",motion:"findNext",motionArgs:{forward:!1}},{keys:["x"],type:"operatorMotion",operator:"delete",motion:"moveByCharacters",motionArgs:{forward:!0},operatorMotionArgs:{visualLine:!1}},{keys:["X"],type:"operatorMotion",operator:"delete",motion:"moveByCharacters",motionArgs:{forward:!1},operatorMotionArgs:{visualLine:!0}},{keys:["D"],type:"operatorMotion",operator:"delete",motion:"moveToEol",
motionArgs:{inclusive:!0},operatorMotionArgs:{visualLine:!0}},{keys:["Y"],type:"operatorMotion",operator:"yank",motion:"moveToEol",motionArgs:{inclusive:!0},operatorMotionArgs:{visualLine:!0}},{keys:["C"],type:"operatorMotion",operator:"change",operatorArgs:{enterInsertMode:!0},motion:"moveToEol",motionArgs:{inclusive:!0},operatorMotionArgs:{visualLine:!0}},{keys:["~"],type:"operatorMotion",operator:"swapcase",motion:"moveByCharacters",motionArgs:{forward:!0}},{keys:["a"],type:"action",action:"enterInsertMode",
actionArgs:{insertAt:"charAfter"}},{keys:["A"],type:"action",action:"enterInsertMode",actionArgs:{insertAt:"eol"}},{keys:["i"],type:"action",action:"enterInsertMode"},{keys:["I"],type:"action",action:"enterInsertMode",motion:"moveToFirstNonWhiteSpaceCharacter"},{keys:["o"],type:"action",action:"newLineAndEnterInsertMode",actionArgs:{after:!0}},{keys:["O"],type:"action",action:"newLineAndEnterInsertMode",actionArgs:{after:!1}},{keys:["v"],type:"action",action:"toggleVisualMode"},{keys:["V"],type:"action",
action:"toggleVisualMode",actionArgs:{linewise:!0}},{keys:["J"],type:"action",action:"joinLines"},{keys:["p"],type:"action",action:"paste",actionArgs:{after:!0}},{keys:["P"],type:"action",action:"paste",actionArgs:{after:!1}},{keys:["r","character"],type:"action",action:"replace"},{keys:["u"],type:"action",action:"undo"},{keys:["Ctrl-r"],type:"action",action:"redo"},{keys:["m","character"],type:"action",action:"setMark"},{keys:['"',"character"],type:"action",action:"setRegister"},{keys:["z","z"],
type:"action",action:"scrollToCursor",actionArgs:{position:"center"}},{keys:["z","."],type:"action",action:"scrollToCursor",actionArgs:{position:"center"},motion:"moveToFirstNonWhiteSpaceCharacter"},{keys:["z","t"],type:"action",action:"scrollToCursor",actionArgs:{position:"top"}},{keys:["z","Enter"],type:"action",action:"scrollToCursor",actionArgs:{position:"top"},motion:"moveToFirstNonWhiteSpaceCharacter"},{keys:["z","-"],type:"action",action:"scrollToCursor",actionArgs:{position:"bottom"}},{keys:["z",
"b"],type:"action",action:"scrollToCursor",actionArgs:{position:"bottom"},motion:"moveToFirstNonWhiteSpaceCharacter"},{keys:["."],type:"action",action:"repeatLastEdit"},{keys:["a","character"],type:"motion",motion:"textObjectManipulation"},{keys:["i","character"],type:"motion",motion:"textObjectManipulation",motionArgs:{textObjectInner:!0}},{keys:["/"],type:"search",searchArgs:{forward:!0,querySrc:"prompt"}},{keys:["?"],type:"search",searchArgs:{forward:!1,querySrc:"prompt"}},{keys:["*"],type:"search",
searchArgs:{forward:!0,querySrc:"wordUnderCursor"}},{keys:["#"],type:"search",searchArgs:{forward:!1,querySrc:"wordUnderCursor"}},{keys:[":"],type:"ex"}],R=function(){function T(a,b){for(var c=[],d=a;d<a+b;d++)c.push(String.fromCharCode(d));return c}function E(a){return/^[A-Z]$/.test(a)}function F(a,b){for(var c=0;c<b.length;c++)if(b[c]==a)return!0;return!1}function r(){K||(K={searchQuery:null,searchIsReversed:!1,registerController:new aa({})});return K}function y(a){a.vimState||(a.vimState={inputState:new x,
lastHPos:-1,lastHSPos:-1,lastMotion:null,marks:{},visualMode:!1,visualLine:!1});return a.vimState}function x(){this.prefixRepeat=[];this.motionRepeat=[];this.motionArgs=this.motion=this.operatorArgs=this.operator=null;this.keyBuffer=[];this.registerName=null}function B(a,b){this.clear();a&&this.set(a,b)}function aa(a){this.registers=a;this.unamedRegister=a['"']=new B}function z(a,b,c){var d=Math.min(Math.max(a.firstLine(),b.line),a.lastLine());a=v(a,d)-1;a=c?a+1:a;b=Math.min(Math.max(0,b.ch),a);return{line:d,
ch:b}}function L(a){var b={},c;for(c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);return b}function ba(a,b,c){return{line:a.line+b,ch:a.ch+c}}function ca(a,b,c){return function(){for(var d=0;d<c;d++)b(a)}}function C(a,b){return a.ch==b.ch&&a.line==b.line}function p(a,b){return a.line<b.line||a.line==b.line&&a.ch<b.ch?!0:!1}function da(a,b,c){a=p(a,b);b=p(b,c);return a&&b}function v(a,b){return a.getLine(b).length}function D(a,b){b.visualMode=!1;b.visualLine=!1;var c=a.getCursor("anchor"),d=a.getCursor("head");
C(c,d)||a.setCursor(z(a,d))}function A(a){if(!a)return 0;var b=a.search(/\S/);return-1==b?a.length:b}function M(a,b,c,d,e){c=a.getCursor();var f=a.getLine(c.line);a=c.ch;var g=f.substring(a);e=e?g.search(/\w/):g.search(/\S/);if(-1==e)return null;a+=e;g=f.substring(a);e=f.substring(0,a);d=d?/^\S+/:/\w/.test(f.charAt(a))?/^\w+/:/^[^\w\s]+/;g=d.exec(g);f=a;a=a+g[0].length-1;(d=d.exec(e.split("").reverse().join("")))&&(f-=d[0].length);b&&a++;return{start:{line:c.line,ch:f},end:{line:c.line,ch:a}}}function ea(a,
b,c,d){for(var e=a.getCursor(),f=e.ch,g,h=0;h<b;h++){g=a.getLine(e.line);var l=d,k=void 0;g=k=c?g.indexOf(l,f+1):g.lastIndexOf(l,f-1);if(-1==g)return null;f=g}return{line:a.getCursor().line,ch:g}}function G(a,b,c,d){F(c,qa)&&(b.marks[c]&&b.marks[c].clear(),b.marks[c]=a.setBookmark(d))}function U(a,b,c){var d=b.line;c=c?c:a.getLine(d).charAt(b.ch);F(c,["(","[","{"]);var e={"(":")",")":"(","[":"]","]":"[","{":"}","}":"{"}[c];if(!e)return b;for(var f={"(":1,"{":1,"[":1}[c]||-1,g=1,h=c,l=b.ch,k=a.getLine(d);h&&
0<g;)l+=f,h=k.charAt(l),h||(d+=f,k=a.getLine(d)||"",0<f?l=0:(h=k.length,l=0<h?h-1:0),h=k.charAt(l)),h===c?g++:h===e&&g--;return h?{line:d,ch:l}:b}function V(a,b,c){var d=a.getCursor();b=U(a,d,b);a=U(a,b);a.ch+=c?1:0;b.ch+=c?0:1;return{start:a,end:b}}function fa(a,b,c){var d=a.getCursor();a=a.getLine(d.line).split("");var e,f,g,h;g=a.indexOf(b);d.ch<g?d.ch=g:g<d.ch&&a[d.ch]==b&&(f=d.ch,--d.ch);if(a[d.ch]!=b||f)for(g=d.ch;-1<g&&!e;g--)a[g]==b&&(e=g+1);else e=d.ch+1;if(e&&!f)for(g=e,h=a.length;g<h&&
!f;g++)a[g]==b&&(f=g);if(!e||!f)return{start:d,end:d};c&&(--e,++f);return{start:{line:d.line,ch:e},end:{line:d.line,ch:f}}}function ga(){}function t(a){a=y(a);return a.searchState_||(a.searchState_=new ga)}function ha(a){for(var b=!1,c=[],d=0;d<a.length;d++){var e=a.charAt(d);b||"/"!=e||c.push(d);b="\\"==e}return c}function s(a,b){a.openConfirm?a.openConfirm('<span style="color: red">'+b+'</span> <button type="button">OK</button>',function(){},{bottom:!0}):alert(b)}function W(a,b){var c=(b.prefix||
"")+" "+(b.desc||""),d;d=b.prefix;var e=b.desc,f="";d&&(f+='<span style="font-family: monospace">'+d+"</span>");f+='<input type="text"/> <span style="color: #888">';e&&(f=f+'<span style="color: #888">'+e,f+="</span>");d=f;e=b.onClose;a.openDialog?a.openDialog(d,e,{bottom:!0,value:b.value,onKeyDown:b.onKeyDown,onKeyUp:b.onKeyUp}):e(prompt(c,""))}function N(a,b,c,d){if(b){var e=t(a);c=!!c;d=!!d;if(!(b instanceof RegExp)){var f=ha(b),g,h;f.length?(g=b.substring(0,f[0]),h=-1!=b.substring(f[0]).indexOf("i")):
g=b;g?(d&&(c=/^[^A-Z]*$/.test(g)),b=RegExp(g,c||h?"i":void 0)):b=null}if(b){ia(a,b);a:if(a=e.getQuery(),b instanceof RegExp&&a instanceof RegExp){h=["global","multiline","ignoreCase","source"];for(c=0;c<h.length;c++)if(d=h[c],b[d]!==a[d]){a=!1;break a}a=!0}else a=!1;if(a)return b;e.setQuery(b);return b}}}function ra(a){if("^"==a.source.charAt(0))var b=!0;return{token:function(c){if(b&&!c.sol())c.skipToEnd();else{var d=c.match(a,!1);if(d){if(0==d[0].length){c.next();return}if(!c.sol()&&(c.backUp(1),
!a.exec(c.next()+d[0])))return c.next(),null;c.match(a);return"searching"}for(;!c.eol()&&(c.next(),!c.match(a,!1)););}},query:a}}function ia(a,b){var c=t(a).getOverlay();c&&b==c.query||(c&&a.removeOverlay(c),c=ra(b),a.addOverlay(c),t(a).setOverlay(c))}function ja(a,b,c,d){void 0===d&&(d=1);return a.operation(function(){var e=a.getCursor();b||(e.ch+=1);for(var e=a.getSearchCursor(c,e),f=0;f<d;f++)if(!e.find(b)&&(e=a.getSearchCursor(c,b?{line:a.lastLine()}:{line:a.firstLine(),ch:0}),!e.find(b)))return;
return e.from()})}function X(a){a.removeOverlay(t(a).getOverlay());t(a).setOverlay(null)}function sa(a,b,c){"number"!=typeof a&&(a=a.line);return b instanceof Array?F(a,b):c?a>=b&&a<=c:a==b}function O(a){for(var b=0,c=[];b<a.length;)if("<"!=a.charAt(b))c.push(a.charAt(b)),b++;else{for(var d=++b;">"!=a.charAt(b++););var e=a.substring(d,b-1),d="",f=/^C-(.+)$/.exec(e);f&&(d="Ctrl-",e=f[1]);switch(e){case "BS":e="Backspace";break;case "CR":e="Enter";break;case "Del":e="Delete";break}c.push(d+e)}return c}
function Y(a){a.setCursor(a.getCursor().line,a.getCursor().ch-1,!0);a.setOption("keyMap","vim")}var ta=/[\d]/,ua=[/\w/,/[^\w\s]/],va=[/\S/],H=T(65,26),ka=T(97,26),P=T(48,10),Z="~`!@#$%^&*()_-+=[{}]\\|/?.,<>:;\"'".split(""),la="Left Right Up Down Space Backspace Esc Home End PageUp PageDown Enter".split(" "),qa=H.concat(ka).concat(P).concat(["<",">"]),wa=H.concat(ka).concat(P).concat(["-",'"']),K;x.prototype.pushRepeatDigit=function(a){this.operator?this.motionRepeat=this.motionRepeat.concat(a):this.prefixRepeat=
this.prefixRepeat.concat(a)};x.prototype.getRepeat=function(){var a=0;if(0<this.prefixRepeat.length||0<this.motionRepeat.length)a=1,0<this.prefixRepeat.length&&(a*=parseInt(this.prefixRepeat.join(""),10)),0<this.motionRepeat.length&&(a*=parseInt(this.motionRepeat.join(""),10));return a};B.prototype={set:function(a,b){this.text=a;this.linewise=!!b},append:function(a,b){b||this.linewise?(this.text+="\n"+a,this.linewise=!0):this.text+=a},clear:function(){this.text="";this.linewise=!1},toString:function(){return this.text}};
aa.prototype={pushText:function(a,b,c,d){var e=this.isValidRegister(a)?this.getRegister(a):null;if(e)E(a)?(e.append(c,d),this.unamedRegister.append(c,d)):(e.set(c,d),this.unamedRegister.set(c,d));else{switch(b){case "yank":this.registers["0"]=new B(c,d);break;case "delete":case "change":-1==c.indexOf("\n")?this.registers["-"]=new B(c,d):(this.shiftNumericRegisters_(),this.registers["1"]=new B(c,d))}this.unamedRegister.set(c,d)}},getRegister:function(a){if(!this.isValidRegister(a))return this.unamedRegister;
a=a.toLowerCase();this.registers[a]||(this.registers[a]=new B);return this.registers[a]},isValidRegister:function(a){return a&&F(a,wa)},shiftNumericRegisters_:function(){for(var a=9;2<=a;a--)this.registers[a]=this.getRegister(""+(a-1))}};var I={matchCommand:function(a,b,c){c=c.inputState;for(var d=c.keyBuffer.concat(a),e=0;e<b.length;e++){var f=b[e],g;a:{g=f.keys;for(var h=0;h<d.length;h++)if(d[h]!=g[h]&&"character"!=g[h]){g=!1;break a}g=!0}if(g){if(d.length<f.keys.length)return c.keyBuffer.push(a),
null;if(!c.operator||"action"!=f.type){if("character"==f.keys[d.length-1]&&(c.selectedCharacter=d[d.length-1],1<c.selectedCharacter.length))switch(c.selectedCharacter){case "Enter":c.selectedCharacter="\n";break;case "Space":c.selectedCharacter=" ";break;default:continue}c.keyBuffer=[];return f}}}c.keyBuffer=[];return null},processCommand:function(a,b,c){b.inputState.repeatOverride=c.repeatOverride;switch(c.type){case "motion":this.processMotion(a,b,c);break;case "operator":this.processOperator(a,
b,c);break;case "operatorMotion":this.processOperatorMotion(a,b,c);break;case "action":this.processAction(a,b,c);break;case "search":this.processSearch(a,b,c);break;case "ex":case "keyToEx":this.processEx(a,b,c)}},processMotion:function(a,b,c){b.inputState.motion=c.motion;b.inputState.motionArgs=L(c.motionArgs);this.evalInput(a,b)},processOperator:function(a,b,c){var d=b.inputState;if(d.operator){if(d.operator==c.operator){d.motion="expandToLine";d.motionArgs={linewise:!0};this.evalInput(a,b);return}b.inputState=
new x}d.operator=c.operator;d.operatorArgs=L(c.operatorArgs);b.visualMode&&this.evalInput(a,b)},processOperatorMotion:function(a,b,c){var d=b.visualMode,e=L(c.operatorMotionArgs);e&&d&&e.visualLine&&(b.visualLine=!0);this.processOperator(a,b,c);d||this.processMotion(a,b,c)},processAction:function(a,b,c){var d=b.inputState,e=d.getRepeat(),f=!!e,g=L(c.actionArgs)||{};d.selectedCharacter&&(g.selectedCharacter=d.selectedCharacter);c.operator&&this.processOperator(a,b,c);c.motion&&this.processMotion(a,
b,c);(c.motion||c.operator)&&this.evalInput(a,b);g.repeat=e||1;g.repeatIsExplicit=f;g.registerName=d.registerName;b.inputState=new x;b.lastMotion=null;ma[c.action](a,g,b)},processSearch:function(a,b,c){function d(c,d,e){try{N(a,c,d,e)}catch(f){s(a,"Invalid regex: "+regexPart);return}I.processMotion(a,b,{type:"motion",motion:"findNext",motionArgs:{forward:!0}})}function e(b){a.scrollTo(n.left,n.top);d(b,!0,!0)}function f(b,c){var d;try{d=N(a,c,!0,!0)}catch(e){}d?a.scrollIntoView(ja(a,!h,d),30):(X(a),
a.scrollTo(n.left,n.top))}function g(b,c,d){c=CodeMirror.keyName(b);if("Esc"==c||"Ctrl-C"==c||"Ctrl-["==c)N(a,k),X(a),a.scrollTo(n.left,n.top),CodeMirror.e_stop(b),d(),a.focus()}if(a.getSearchCursor){var h=c.searchArgs.forward;t(a).setReversed(!h);var l=h?"/":"?",k=t(a).getQuery(),n=a.getScrollInfo();switch(c.searchArgs.querySrc){case "prompt":W(a,{onClose:e,prefix:l,desc:xa,onKeyUp:f,onKeyDown:g});break;case "wordUnderCursor":c=M(a,!1,!0,!1,!0);l=!0;c||(c=M(a,!1,!0,!1,!1),l=!1);if(!c)break;var u=
a.getLine(c.start.line).substring(c.start.ch,c.end.ch+1),u=l?"\\b"+u+"\\b":u.replace(/([.?*+$\[\]\/\\(){}|\-])/g,"\\$1");a.setCursor(c.start);d(u,!0,!1)}}},processEx:function(a,b,c){function d(b){J.processCommand(a,b)}function e(b,c,d){c=CodeMirror.keyName(b);if("Esc"==c||"Ctrl-C"==c||"Ctrl-["==c)CodeMirror.e_stop(b),d(),a.focus()}"keyToEx"==c.type?J.processCommand(a,c.exArgs.input):b.visualMode?W(a,{onClose:d,prefix:":",value:"'<,'>",onKeyDown:e}):W(a,{onClose:d,prefix:":",onKeyDown:e})},evalInput:function(a,
b){var c=b.inputState,d=c.motion,e=c.motionArgs||{},f=c.operator,g=c.operatorArgs||{},h=c.registerName,l=a.getCursor("head"),k=a.getCursor("anchor"),n={line:l.line,ch:l.ch},u={line:n.line,ch:n.ch},m,q;f&&this.recordLastEdit(a,b,c);q=void 0!==c.repeatOverride?c.repeatOverride:c.getRepeat();if(0<q&&e.explicitRepeat)e.repeatIsExplicit=!0;else if(e.noRepeat||!e.explicitRepeat&&0===q)q=1,e.repeatIsExplicit=!1;c.selectedCharacter&&(e.selectedCharacter=g.selectedCharacter=c.selectedCharacter);e.repeat=q;
b.inputState=new x;if(d){m=Q[d](a,e,b);b.lastMotion=Q[d];if(!m)return;m instanceof Array&&(n=m[0],m=m[1]);m||(m={ch:n.ch,line:n.line});b.visualMode?(p(k,l)&&(C(k,m)||p(m,k))?k.ch+=1:p(l,k)&&(C(k,m)||p(k,m))&&(k.ch-=1),l=m,b.visualLine&&(p(k,l)?(k.ch=0,l.ch=v(a,l.line)):(l.ch=0,k.ch=v(a,k.line))),a.setSelection(k,l),G(a,b,"<",p(k,l)?k:l),G(a,b,">",p(k,l)?l:k)):f||(m=z(a,m),a.setCursor(m.line,m.ch))}if(f){d=!1;b.lastMotion=null;g.repeat=q;b.visualMode&&(n=k,m=l,e.inclusive=!0);p(m,n)&&(l=n,n=m,m=l,
d=!0);!e.inclusive||b.visualMode&&d||m.ch++;if(l=e.linewise||b.visualMode&&b.visualLine)e=m,n.ch=0,e.ch=0,e.line++;else if(e.forward){e=m;k=a.getRange(n,e).split("\n");if(q=1<k.length)k=k.pop(),q=/^\s*$/.test(k);q&&(e.line--,e.ch=v(a,e.line))}g.registerName=h;g.linewise=l;ya[f](a,g,b,n,m,u);b.visualMode&&D(a,b);g.enterInsertMode&&ma.enterInsertMode(a)}},recordLastEdit:function(a,b,c){b.lastEdit=c}},Q={expandToLine:function(a,b){return{line:a.getCursor().line+b.repeat-1,ch:Infinity}},findNext:function(a,
b,c){c=t(a);var d=c.getQuery();if(d){var e=!b.forward,e=c.isReversed()?!e:e;ia(a,d);return ja(a,e,d,b.repeat)}},goToMark:function(a,b,c){return(a=c.marks[b.selectedCharacter])?a.find():null},jumpToMark:function(a,b,c){for(var d=a.getCursor(),e=0;e<b.repeat;e++){var f=d,g;for(g in c.marks)if(/^[a-z]$/.test(g)){var h=c.marks[g].find();if(b.forward?!p(h,f):!p(f,h))if(!b.linewise||h.line!=f.line){var l=C(f,d),k=b.forward?da(f,h,d):da(d,h,f);if(l||k)d=h}}}b.linewise&&(d.ch=A(a.getLine(d.line)));return d},
moveByCharacters:function(a,b){var c=a.getCursor(),d=b.repeat;return{line:c.line,ch:b.forward?c.ch+d:c.ch-d}},moveByLines:function(a,b,c){var d=a.getCursor(),e=d.ch;switch(c.lastMotion){case this.moveByLines:case this.moveByDisplayLines:case this.moveToColumn:case this.moveToEol:e=c.lastHPos;break;default:c.lastHPos=e}var f=b.repeat+(b.repeatOffset||0),d=b.forward?d.line+f:d.line-f;if(d<a.firstLine()||d>a.lastLine())return null;b.toFirstChar&&(e=A(a.getLine(d)),c.lastHPos=e);c.lastHSPos=a.charCoords({line:d,
ch:e},"div").left;return{line:d,ch:e}},moveByDisplayLines:function(a,b,c){var d=a.getCursor();switch(c.lastMotion){case this.moveByDisplayLines:case this.moveByLines:case this.moveToColumn:case this.moveToEol:break;default:c.lastHSPos=a.charCoords(d,"div").left}var e=b.repeat;a=a.findPosV(d,b.forward?e:-e,"line",c.lastHSPos);if(a.hitSide)return null;c.lastHPos=a.ch;return a},moveByPage:function(a,b){var c=a.getCursor(),d=b.repeat;a.moveV(b.forward?d:-d,"page");d=a.getCursor();a.setCursor(c);return d},
moveByParagraph:function(a,b){for(var c=a.getCursor().line,d=b.repeat,e=b.forward?1:-1,f=0;f<d&&!(!b.forward&&c===a.firstLine()||b.forward&&c==a.lastLine());f++)for(c+=e;c!==a.firstLine()&&c!=a.lastLine()&&a.getLine(c);)c+=e;return{line:c,ch:0}},moveByWords:function(a,b){var c;a:{c=b.repeat;for(var d=!!b.forward,e=!!b.wordEnd,f=!!b.bigWord,g=a.getCursor(),h=0;h<c;h++)for(var l=g.line,k,n=!1;!n;){b:{k=a;for(var n=g,u=d,m=f,q=n.line,w=n.ch,p=k.getLine(q),u=u?1:-1,m=m?va:ua;;){for(var s=0<u?p.length:
-1,r=s,t=s;w!=s;){for(var y=!1,x=0;x<m.length&&!y;++x)if(m[x].test(p.charAt(w))){for(r=w;w!=s&&m[x].test(p.charAt(w));)w+=u;t=w;y=r!=t;if(r!=n.ch||q!=n.line||t!=r+u){k={from:Math.min(r,t+1),to:Math.max(r,t),line:q};break b}}y||(w+=u)}q+=u;w=k;p=q;if(!(p>=w.firstLine()&&p<=w.lastLine())){k=null;break b}p=k.getLine(q);w=0<u?0:p.length}throw"The impossible happened.";}n=!0;if(k)g.line=k.line,d&&e?g.ch=k.to-1:d&&!e?(q=g.ch,q>=k.from&&q<=k.to&&k.line==l?(n=!1,g.ch=k.to-1):g.ch=k.from):!d&&e?(q=g.ch,q>=
k.from&&q<=k.to&&k.line==l?(n=!1,g.ch=k.from):g.ch=k.to):d||e||(g.ch=k.from);else{c=d?{line:g.line,ch:v(a,g.line)}:{line:g.line,ch:0};break a}}c=g}return c},moveTillCharacter:function(a,b){var c=ea(a,b.repeat,b.forward,b.selectedCharacter);if(!c)return a.getCursor();c.ch+=b.forward?-1:1;return c},moveToCharacter:function(a,b){return ea(a,b.repeat,b.forward,b.selectedCharacter)||a.getCursor()},moveToColumn:function(a,b,c){b=b.repeat;c.lastHPos=b-1;c.lastHSPos=a.charCoords(a.getCursor(),"div").left;
c=a.getCursor().line;return z(a,{line:c,ch:b-1})},moveToEol:function(a,b,c){var d=a.getCursor();c.lastHPos=Infinity;b={line:d.line+b.repeat-1,ch:Infinity};d=a.clipPos(b);d.ch--;c.lastHSPos=a.charCoords(d,"div").left;return b},moveToFirstNonWhiteSpaceCharacter:function(a){var b=a.getCursor();return{line:b.line,ch:A(a.getLine(b.line))}},moveToMatchedSymbol:function(a,b){var c=a.getCursor(),d=a.getLine(c.line).charAt(c.ch);return-1!="()[]{}".indexOf(d)?U(a,a.getCursor(),b.symbol):c},moveToStartOfLine:function(a){return{line:a.getCursor().line,
ch:0}},moveToLineOrEdgeOfDocument:function(a,b){var c=b.forward?a.lastLine():a.firstLine();b.repeatIsExplicit&&(c=b.repeat-a.getOption("firstLineNumber"));return{line:c,ch:A(a.getLine(c))}},textObjectManipulation:function(a,b){var c=b.selectedCharacter;if(!na[c])return null;c=na[c](a,!b.textObjectInner);return[c.start,c.end]}},ya={change:function(a,b,c,d,e){r().registerController.pushText(b.registerName,"change",a.getRange(d,e),b.linewise);b.linewise?(d.ch=A(a.getLine(d.line)),a.replaceRange("\n",
d,e)):a.replaceRange("",d,e);a.setCursor(d)},"delete":function(a,b,c,d,e){r().registerController.pushText(b.registerName,"delete",a.getRange(d,e),b.linewise);a.replaceRange("",d,e);b.linewise?a.setCursor(Q.moveToFirstNonWhiteSpaceCharacter(a)):a.setCursor(d)},indent:function(a,b,c,d,e){var f=d.line;e=e.line;c=c.visualMode?b.repeat:1;for(b.linewise&&e--;f<=e;f++)for(var g=0;g<c;g++)a.indentLine(f,b.indentRight);a.setCursor(d);a.setCursor(Q.moveToFirstNonWhiteSpaceCharacter(a))},swapcase:function(a,
b,c,d,e,f){b=a.getRange(d,e);c="";for(var g=0;g<b.length;g++){var h=b.charAt(g);c+=E(h)?h.toLowerCase():h.toUpperCase()}a.replaceRange(c,d,e);a.setCursor(f)},yank:function(a,b,c,d,e,f){r().registerController.pushText(b.registerName,"yank",a.getRange(d,e),b.linewise);a.setCursor(f)}},ma={scrollToCursor:function(a,b){var c=a.getCursor().line,d=window.getComputedStyle(a.getScrollerElement()).getPropertyValue("height"),d=parseInt(d),c=a.charCoords({line:c,ch:0},"local").top;parseInt(d);switch(b.position){case "center":c=
c-d/2+10;break;case "bottom":c-=d}a.scrollTo(null,c);a.scrollIntoView()},enterInsertMode:function(a,b){var c=b?b.insertAt:null;"eol"==c?(c=a.getCursor(),c={line:c.line,ch:v(a,c.line)},a.setCursor(c)):"charAfter"==c&&a.setCursor(ba(a.getCursor(),0,1));a.setOption("keyMap","vim-insert")},toggleVisualMode:function(a,b,c){var d=b.repeat,e=a.getCursor();c.visualMode?(e=a.getCursor("anchor"),d=a.getCursor("head"),!c.visualLine&&b.linewise?(c.visualLine=!0,e.ch=p(e,d)?0:v(a,e.line),d.ch=p(e,d)?v(a,d.line):
0,a.setSelection(e,d)):c.visualLine&&!b.linewise?c.visualLine=!1:D(a,c)):(c.visualMode=!0,c.visualLine=!!b.linewise,c.visualLine?(e.ch=0,d=z(a,{line:e.line+d-1,ch:v(a,e.line)},!0)):d=z(a,{line:e.line,ch:e.ch+d},!0),b.repeatIsExplicit||c.visualLine?a.setSelection(e,d):(a.setCursor(d),a.setSelection(d,e)));G(a,c,"<",p(e,d)?e:d);G(a,c,">",p(e,d)?d:e)},joinLines:function(a,b,c){var d,e;c.visualMode?(d=a.getCursor("anchor"),e=a.getCursor("head"),e.ch=v(a,e.line)-1):(b=Math.max(b.repeat,2),d=a.getCursor(),
e=z(a,{line:d.line+b-1,ch:Infinity}));var f=0;a.operation(function(){for(var b=d.line;b<e.line;b++){f=v(a,d.line);var c={line:d.line+1,ch:v(a,d.line+1)},l=a.getRange(d,c),l=l.replace(/\n\s*/g," ");a.replaceRange(l,d,c)}a.setCursor({line:d.line,ch:f})})},newLineAndEnterInsertMode:function(a,b){var c=a.getCursor();c.line!==a.firstLine()||b.after?(c.line=b.after?c.line:c.line-1,c.ch=v(a,c.line),a.setCursor(c),(CodeMirror.commands.newlineAndIndentContinueComment||CodeMirror.commands.newlineAndIndent)(a)):
(a.replaceRange("\n",{line:a.firstLine(),ch:0}),a.setCursor(a.firstLine(),0));this.enterInsertMode(a)},paste:function(a,b,c){var d=a.getCursor(),e=r().registerController.getRegister(b.registerName);if(e.text){c="";for(var f=0;f<b.repeat;f++)c+=e.text;(e=e.linewise)?b.after?(c="\n"+c.slice(0,c.length-1),d.ch=v(a,d.line)):d.ch=0:d.ch+=b.after?1:0;a.replaceRange(c,d);e&&b.after?b={line:d.line+1,ch:A(a.getLine(d.line+1))}:e&&!b.after?b={line:d.line,ch:A(a.getLine(d.line))}:!e&&b.after?(b=a.indexFromPos(d),
b=a.posFromIndex(b+c.length-1)):(b=a.indexFromPos(d),b=a.posFromIndex(b+c.length));a.setCursor(b)}},undo:function(a,b){ca(a,CodeMirror.commands.undo,b.repeat)()},redo:function(a,b){ca(a,CodeMirror.commands.redo,b.repeat)()},setRegister:function(a,b,c){c.inputState.registerName=b.selectedCharacter},setMark:function(a,b,c){G(a,c,b.selectedCharacter,a.getCursor())},replace:function(a,b,c){var d=b.selectedCharacter,e=a.getCursor(),f;c.visualMode?(e=a.getCursor("start"),f=a.getCursor("end"),f=a.clipPos({line:f.line,
ch:f.ch+1})):(f=a.getLine(e.line),b=e.ch+b.repeat,b>f.length&&(b=f.length),f={line:e.line,ch:b});"\n"==d?(c.visualMode||a.replaceRange("",e,f),(CodeMirror.commands.newlineAndIndentContinueComment||CodeMirror.commands.newlineAndIndent)(a)):(b=a.getRange(e,f),b=b.replace(/[^\n]/g,d),a.replaceRange(b,e,f),c.visualMode?(a.setCursor(e),D(a,c)):a.setCursor(ba(f,0,-1)))},repeatLastEdit:function(a,b,c){c.lastEdit&&(b.repeat&&b.repeatIsExplicit&&(c.lastEdit.repeatOverride=b.repeat),b=c.inputState,c.inputState=
c.lastEdit,I.evalInput(a,c),c.inputState=b)}},na={w:function(a,b){return M(a,b,!0,!1)},W:function(a,b){return M(a,b,!0,!0)},"{":function(a,b){return V(a,"}",b)},"(":function(a,b){return V(a,")",b)},"[":function(a,b){return V(a,"]",b)},"'":function(a,b){return fa(a,"'",b)},'"':function(a,b){return fa(a,'"',b)}};ga.prototype={getQuery:function(){return r().query},setQuery:function(a){r().query=a},getOverlay:function(){return this.searchOverlay},setOverlay:function(a){this.searchOverlay=a},isReversed:function(){return r().isReversed},
setReversed:function(a){r().isReversed=a}};var xa="(Javascript regexp)",oa=[{name:"map",type:"builtIn"},{name:"saveI",shortName:"w!",type:"builtIn"},{name:"save",shortName:"w",type:"builtIn"},{name:"closeI",shortName:"q!",type:"builtIn"},{name:"close",shortName:"q",type:"builtIn"},{name:"saveAndCloseI",shortName:"wq!",type:"builtIn"},{name:"saveAndClose",shortName:"wq",type:"builtIn"},{name:"undo",shortName:"u",type:"builtIn"},{name:"redo",shortName:"red",type:"builtIn"},{name:"substitute",shortName:"s",
type:"builtIn"},{name:"nohlsearch",shortName:"noh",type:"builtIn"},{name:"delmarks",shortName:"delm",type:"builtin"}];R.ExCommandDispatcher=function(){this.buildCommandMap_()};R.ExCommandDispatcher.prototype={processCommand:function(a,b){var c=new CodeMirror.StringStream(b),d={};d.input=b;try{this.parseInput_(a,c,d)}catch(e){s(a,e);return}var f;if(d.commandName){var g=this.matchCommand_(d.commandName);if(g){f=g.name;this.parseCommandArgs_(c,d,g);if("exToKey"==g.type){for(c=0;c<g.toKeys.length;c++)$.handleKey(a,
g.toKeys[c]);return}if("exToEx"==g.type){this.processCommand(a,g.toInput);return}}}else void 0!==d.line&&(f="move");if(f)pa[f](a,d);else s(a,'Not an editor command ":'+b+'"')},parseInput_:function(a,b,c){b.eatWhile(":");b.eat("%")?(c.line=a.firstLine(),c.lineEnd=a.lastLine()):(c.line=this.parseLineSpec_(a,b),void 0!==c.line&&b.eat(",")&&(c.lineEnd=this.parseLineSpec_(a,b)));a=b.match(/^(\w+)/);c.commandName=a?a[1]:b.match(/.*/)[0];return c},parseLineSpec_:function(a,b){var c=b.match(/^(\d+)/);if(c)return parseInt(c[1],
10)-1;switch(b.next()){case ".":return a.getCursor().line;case "$":return a.lastLine();case "'":if((c=y(a).marks[b.next()])&&c.find())return c.find().line;throw"Mark not set";default:return b.backUp(1),a.getCursor().line}},parseCommandArgs_:function(a,b,c){a.eol()||(b.argString=a.match(/.*/)[0],a=c.argDelimiter||/\s+/,c=b.argString,c=c.trim?c.trim():c.replace(/^\s+|\s+$/g,""),a=c.split(a),a.length&&a[0]&&(b.args=a))},matchCommand_:function(a){for(var b=a.length;0<b;b--){var c=a.substring(0,b);if(this.commandMap_[c]&&
(c=this.commandMap_[c],0===c.shortName.indexOf(a)))return c}return null},buildCommandMap_:function(){this.commandMap_={};for(var a=0;a<oa.length;a++){var b=oa[a];this.commandMap_[b.shortName||b.name]=b}},map:function(a,b){if(":"!=a&&":"==a.charAt(0)){var c=a.substring(1);":"!=b&&":"==b.charAt(0)?this.commandMap_[c]={name:c,type:"exToEx",toInput:b.substring(1)}:this.commandMap_[c]={name:c,type:"exToKey",toKeys:O(b)}}else":"!=b&&":"==b.charAt(0)?S.unshift({keys:O(a),type:"keyToEx",exArgs:{input:b.substring(1)}}):
S.unshift({keys:O(a),type:"keyToKey",toKeys:O(b)})}};var pa={map:function(a,b){var c=b.args;!c||2>c.length?a&&s(a,"Invalid mapping: "+b.input):J.map(c[0],c[1],a)},move:function(a,b){I.processCommand(a,y(a),{type:"motion",motion:"moveToLineOrEdgeOfDocument",motionArgs:{forward:!1,explicitRepeat:!0,linewise:!0},repeatOverride:b.line+1})},substitute:function(a,b){function c(){for(var b=a.getSearchCursor(n,q);b.findNext()&&sa(b.from(),p,m);){var c=a.getRange(b.from(),b.to()).replace(n,g);b.replace(c)}b=
y(a);b.visualMode&&D(a,b)}var d=b.argString,e=ha(d);if(0!==e[0])s(a,"Substitutions should be of the form :s/pattern/replace/");else{var f=d.substring(e[0]+1,e[1]),g="",h,l;e[1]&&(g=d.substring(e[1]+1,e[2]));e[2]&&(d=d.substring(e[2]+1).split(" "),h=d[0],l=parseInt(d[1]));h&&(f=f+"/"+h);if(f)try{N(a,f,!0,!0)}catch(k){s(a,"Invalid regex: "+f);return}var n=t(a).getQuery(),p=b.line||a.firstLine(),m=b.lineEnd||p;l&&(p=m,m=p+l-1);var q=z(a,{line:p,ch:0});a.operation(c)}},redo:CodeMirror.commands.redo,undo:CodeMirror.commands.undo,
save:function(a,b){this.write(a,b)},saveAndClose:function(a,b){this.write(a,b);this.close(a,b)},close:function(a,b){CodeMirror.commands.close?CodeMirror.commands.close(a,"!"==b.argString):a.close("!"==b.argString)},write:function(a,b,c){CodeMirror.commands.save?CodeMirror.commands.save(a,"!"==b.argString):a.save("!"==b.argString)},nohlsearch:function(a){X(a)},delmarks:function(a,b){if(b.argString&&b.argString.trim())for(var c=y(a),d=new CodeMirror.StringStream(b.argString.trim());!d.eol();){d.eatSpace();
var e=d.pos;if(!d.match(/[a-zA-Z]/,!1)){s(a,"Invalid argument: "+b.argString.substring(e));break}var f=d.next();if(d.match("-",!0)){if(!d.match(/[a-zA-Z]/,!1)){s(a,"Invalid argument: "+b.argString.substring(e));break}var g=d.next();if(/^[a-z]$/.test(f)&&/^[a-z]$/.test(g)||E(f)&&E(g)){f=f.charCodeAt(0);g=g.charCodeAt(0);if(f>=g){s(a,"Invalid argument: "+b.argString.substring(e));break}for(e=0;e<=g-f;e++){var h=String.fromCharCode(f+e);delete c.marks[h]}}else{s(a,"Invalid argument: "+f+"-");break}}else delete c.marks[f]}else s(a,
"Argument required")}},J=new R.ExCommandDispatcher;CodeMirror.keyMap.vim=function(){function a(a,b){return function(c){var g=a,h=b;E(g)&&("Shift"==h?h=null:g=g.toLowerCase());h&&(g=h+"-"+g);$.handleKey(c,g)}}function b(b,e){for(var f=0;f<b.length;f++){var g=b[f];!e&&F(g,Z)&&(g="'"+g+"'");e?c[e+"-"+g]=a(b[f],e):c[g]=a(b[f])}}var c={nofallthrough:!0,style:"fat-cursor"};b(H);b(H,"Shift");b(H,"Ctrl");b(Z);b(Z,"Ctrl");b(P);b(P,"Ctrl");b(la);b(la,"Ctrl");return c}();CodeMirror.keyMap["vim-insert"]={Esc:Y,
"Ctrl-[":Y,"Ctrl-C":Y,"Ctrl-N":"autocomplete","Ctrl-P":"autocomplete",Enter:function(a){(CodeMirror.commands.newlineAndIndentContinueComment||CodeMirror.commands.newlineAndIndent)(a)},fallthrough:["default"]};return{buildKeyMap:function(){},getRegisterController:function(){return r().registerController},clearVimGlobalState_:function(){K=null},map:function(a,b){J.map(a,b)},defineEx:function(a,b,c){if(0===a.indexOf(b))pa[a]=c,J.commandMap_[b]={name:a,shortName:b,type:"api"};else throw Error('(Vim.defineEx) "'+
b+'" is not a prefix of "'+a+'", command not registered');},maybeInitState:function(a){y(a)},handleKey:function(a,b){var c,d=y(a);if("Esc"==b)d.inputState=new x,d.visualMode&&D(a,d);else{d.visualMode&&C(a.getCursor("head"),a.getCursor("anchor"))&&D(a,d);d.visualMode||C(a.getCursor("head"),a.getCursor("anchor"))||(d.visualMode=!0,d.visualLine=!1);if("0"!=b||"0"==b&&0===d.inputState.getRepeat())c=I.matchCommand(b,S,d);if(c)if("keyToKey"==c.type)for(d=0;d<c.toKeys.length;d++)this.handleKey(a,c.toKeys[d]);
else I.processCommand(a,d,c);else ta.test(b)&&d.inputState.pushRepeatDigit(b)}}}},$=R();CodeMirror.Vim=$})();
