var D=!0;
Registry.require(["pingpong","crcrc","layout/default/htmlutil","i18n","layout/default/layout_helper"],function(){var z=Registry.prepare(),m=Registry.get("crcrc").cr,l=Registry.get("crcrc").crc,p=Registry.get("layout/default/htmlutil"),k=Registry.get("i18n"),u=Registry.get("layout"),v=Registry.get("layout/default/layout_helper"),r=v.images;u.render(function(){var n={};v.addStyle();v.addFont();var u=function(c,a){var d=[];if(a.sub_menu_item){var b=l("table","actiontable","actiontable-"+a.name);w(b,
a.items);d.push(b)}else if(b=null,a.image?b=p.createImage(r.get(a.image),a.name,a.id,null,""):a.enabler&&(b=p.createImage(chrome.extension.getURL(n.enabled?"/layout/default/images/button_ok.png":"/layout/default/images/cancel.png"),a.name,a.uuid,null,"")),b&&d.push(b),a.url||a.urls){for(var b=m("span",a.name,a.id,"urls"),e=a.urls||[a],f=0;f<e.length;f++){var g=e[f],h=document.createElement("span");h.textContent=g.name;var s=a.urls?h:b;s.url=g.url;s.newtab=g.newtab;s.addEventListener("click",function(){A(this.url,
this.newtab)});$(s).addClass("clickable");b.appendChild(h);f<e.length-1&&(g=document.createElement("span"),g.textContent=" | ",b.appendChild(g))}d.push(b);a.tamperfire&&function(){var b=function(b,c){d&&1<d.length&&(d[1].textContent=c?c:d[1].textContent.replace("?",Number(b)));d[0]&&d[0].setAttribute("src",r.get(a.doneImage))};a.tabid&&B(a.tabid,b)}()}else if(a.menucmd)b=document.createElement("span"),c.id=a.id,f=function(){C(this.id,window.close)},c.addEventListener("click",f),$(c).addClass("clickable"),
b.textContent=a.name,a.accessKey&&(e=a.accessKey[0].toUpperCase(),E(e,f,c)?(f=RegExp(e,"i"),g=b.textContent.search(f),h=[],-1==g&&(b.textContent+=" ("+e+")",g=b.textContent.search(f)),h.push(b.textContent.substr(0,g)),h.push('<span class="underlined">'),h.push(b.textContent.substr(g,1)),h.push("</span>"),h.push(b.textContent.substr(g+1)),b.innerHTML=h.join("")):console.warn("Registering keyboard shortcut for '"+a.name+"' failed")),d.push(b);else if(a.button)b=l("span",a.display||"",a.name,a.id,"bu",
!0),b.textContent=a.name,c.key=a.id,c.warning=a.warning,c.reload=a.reload,c.addEventListener("click",function(){var a=!0;this.warning&&(a=F(this.warning));a&&G(this.key,{reload:this.reload})}),$(c).addClass("clickable"),d.push(b);else if(a.userscript||a.user_agent){var b=m("span",a.name,a.uuid,"ai"),t;a.uuid&&(f=a.blacklisted?"enabler_warning":a.enabled?"enabler_enabled":"enabler_disabled",g=a.blacklisted?k.getMessage("This_script_is_blacklisted_"):a.enabled?k.getMessage("Enabled"):k.getMessage("Disabled"),
e=function(a){a&&a.button&2||a.button&1||a.ctrlKey?(window.open(chrome.extension.getURL("options.html")+"#open="+this.key),a.stopPropagation()):H(this.uuid,"enabled",!this.oldvalue)},f=p.createEnabler(f,a.uuid,"enabled","enabled",g,e,0<a.position?10>a.position?" "+a.position:a.position:null),f.oldvalue=a.enabled,d.push(f),b.uuid=a.uuid,b.oldvalue=a.enabled,b.key=a.uuid,b.addEventListener("click",e),e=" clickable",a.blacklisted&&(e+=" crossedout",c.setAttribute("title",k.getMessage("This_script_is_blacklisted_"))),
$(c).addClass(e),e=[],a.nnew||a.system||!a.origin||(f=p.createImage(r.get("flag"),"",a.uuid,"issue",k.getMessage("Report_this_as_spam_or_malicious"),function(){x(a.uuid,"hoster")}),e.push(f)),a.nnew||a.system||!a.support||(f=p.createImage(r.get("bug"),"",a.uuid,"bug",k.getMessage("Report_a_bug"),function(){x(a.uuid,"author")}),e.push(f)),e.length&&(t=l("div","actionbuttons",a.uuid,"actions"),e.forEach(function(a){t.appendChild(a)})));b.textContent=a.name;d.push(b);t&&d.push(t)}else b=m("span",a.name,
a.id,"ai"),b.textContent=a.name,d.push(b);return d},w=function(c,a,d){for(var b in a){var e=a[b];if(c||d[e.pos]){var f=c||d[e.pos],g=f?m("tr",e.name,e.uuid||e.id,"outer"):null,h=u(g,e);if(h&&h.length)for(f.appendChild(g),b=0;f=h[b];b++){var l=b==h.length-1?3-b:0,k=m("td","actiontd",e.name,e.uuid||e.id,b);0<l&&k.setAttribute("colspan",l);f&&k.appendChild(f);g.appendChild(k)}}else console.warn("Warn(cAm): unknown pos "+e.pos)}},y=function(c,a){var d=document.getElementById("action"),b=d.parentNode;
b.removeChild(d);d=m("span");d.setAttribute("id","action");b.appendChild(d);b=l("table","actionlayout","actionlayout");d.appendChild(b);var e=l("tr","actionpostr","hor"),d=l("td","actionpostd","hor_west");e.appendChild(d);b.appendChild(e);2===z.ACTIONMENU.COLUMNS&&n.enabled?(b=l("td","actionpostd","hor_east"),e.appendChild(b)):b=d;var e=l("table","actionregion","top"),f=l("table","actionregion","right"),g=l("table","actionregion","left"),h=l("table","actionregion","bottom");d.appendChild(e);b.appendChild(f);
d.appendChild(g);d.appendChild(h);var k={top:e,left:g,right:f,bottom:h};window.setTimeout(function(){w(null,c,k)},1)},A=function(c,a){try{var d=function(b){chrome.tabs.sendMessage(b.id,{method:"loadUrl",url:c,newtab:a},function(a){})};a?sendMessage({method:"newTab",url:c},function(a){}):chrome.tabs.getSelected(null,d)}catch(b){console.warn("lU:",b)}},F=function(c){var a=confirm(c.msg),d={};a&&c.ok?d=c.ok:!a&&c.cancel&&(d=c.cancel);if(c.ok||c.cancel)a=!0;d.url&&sendMessage({method:"newTab",url:d.url},
function(a){});return a},x=function(c,a,d){try{sendMessage({method:"reportAnIssue",uuid:c,to:a},function(a){d&&d()})}catch(b){console.warn("raI:",b)}},G=function(c,a){try{sendMessage({method:"buttonPress",name:c},function(b){a.reload&&window.location.reload()})}catch(d){console.warn("rSU:",d)}},q={},I=function(c,a,d){document.body.addEventListener("keydown",function(a){D&&console.log("MenuCmdKeyListener: check event",a);if(!(a.altKey||a.ctrlKey||a.shiftKey))for(var c in q)if(q.hasOwnProperty(c)){var d=
q[c];d&&a.keyCode==d.key&&(D&&console.log("MenuCmdKeyListener: ... found",a.keyCode,String.fromCharCode(a.keyCode)),d.cb.apply(d.elem||window,[]))}},!1)},E=function(c,a,d){D&&console.log("MenuCmdKeyListener: register accessKey "+c);c=c.charCodeAt(0);if(q[c])return D&&console.log("MenuCmdKeyListener: ...failed!"),!1;q[c]={key:c,cb:a,elem:d};return!0},C=function(c,a){try{sendMessage({method:"execMenuCmd",id:c},function(b){a&&a()})}catch(d){console.warn("Error(eMC):",d)}},B=function(c,a){try{sendMessage({method:"getFireItems",
countonly:!0,tabid:c},function(b){var c=null;if(b.progress){(c=b.progress.action+"... ")&&""!=c||(c="");var d="";b.progress.state&&b.progress.state.of&&(d=" "+Math.round(100*b.progress.state.n/b.progress.state.of)+"%");c=""!=c||""!=d?c+d:null}a(b.cnt,c)})}catch(d){console.warn("Error(gFI):",d)}},H=function(c,a,d){try{c={method:"modifyScriptOptions",uuid:c},a&&""!=a&&(c[a]=d),sendMessage(c,function(a){a&&(a.i18n&&k.setLocale(a.i18n),a.items&&(n=a.options||n,y(a.items)))}),document.getElementById("action").innerHTML=
k.getMessage("Please_wait___")}catch(b){console.warn("Error(mSo): "+b.message)}};chrome.extension.onMessage.addListener(function(c,a,d){D&&console.log("onMessage: method "+c.method);"updateActions"==c.method?window.location.reload():D&&console.log("onMessage: Unknown method '"+c.method+"'")});sendMessage({method:"modifyScriptOptions"},function(c){I();c&&(c.i18n&&k.setLocale(c.i18n),c.items&&(n=c.options||n,y(c.items)))})})});
