window.requestFileSystem||(window.requestFileSystem=window.webkitRequestFileSystem);window.BlobBuilder||(window.BlobBuilder=window.WebKitBlobBuilder);
Registry.require("layout xmlhttprequest convert crcrc curtain layout/default/tabview layout/default/htmlutil helper i18n parser layout/default/layout_helper".split(" "),function(){var m=Registry.get("crcrc").cr,e=Registry.get("crcrc").crc,k=Registry.get("i18n"),u=Registry.get("curtain"),q=Registry.get("helper"),G=Registry.get("layout/default/tabview"),t=Registry.get("layout/default/htmlutil"),y=Registry.get("layout"),z=Registry.get("layout/default/layout_helper"),B=z.images;y.render(function(){z.addStyle();
z.addFont();var y=$.Deferred,f=null,C="???",v=null,w=function(){var a=document.getElementById("ask"),c=e("div","main_container p100100","ask","main");if(a){var b=a.parentNode;b.removeChild(a);b.appendChild(c);document.body.setAttribute("class","main")}var a=e("div","head_container","ask","head_container"),b=e("div","tv_container","ask","tv_container"),g=m("a","head_link","ask","head_link");g.href="http://tampermonkey.net";g.target="_blank";var d=e("div","float margin4","ask","head1"),h=e("img","banner",
"ask");h.src=chrome.extension.getURL("images/icon128.png");var n=e("div","float head margin4","ask","head2"),k=m("div","fire"),f=e("div","version","version","version");f.textContent=" by Jan Biniok";var s=m("div","search","box","");k.textContent="Tampermonkey";d.appendChild(h);n.appendChild(k);n.appendChild(f);g.appendChild(d);g.appendChild(n);a.appendChild(g);a.appendChild(s);c.appendChild(a);c.appendChild(b);c=G.create("_main",b);a=m("div","main","main","tab_content_h");a.textContent=C;b=m("div",
"main","main","tab_content");c.appendTab(q.createUniqueId("main","main"),a,b);u.hide();return b},H=function(a){var c=a.script,b=e("div","viewer_bottom","bottom","");a=e("div","editor_400p_outer","editor",c.name);var g=e("div","editor_400p editor_border","editor",c.name),d=e("textarea","editorta","editor",c.name);d.setAttribute("wrap","off");b.appendChild(a);a.appendChild(g);g.appendChild(d);f.nocm?d.value=c.textContent:window.setTimeout(function(){var a=d.parentNode;a.removeChild(d);b.editor=new MirrorFrame(a,
{value:c.textContent,noButtons:!0,matchBrackets:!0})},1);return b},I=function(){var a={};window.addEventListener("keydown",function(c){var b=!1;if("keydown"==c.type&&(a[c.keyCode]&&(b=a[c.keyCode](c)),b))return c.stopPropagation(),c.preventDefault(),!1},!0);return{registerListener:function(c,b){a[c]=b}}}(),x=function(a,c,b){q.select(b,function(a){return a.label}).forEach(function(b){var d=e("input",c,"tm",b.label);d.type="button";d.value=b.label;d.addEventListener("click",b.fn);a.appendChild(d);b.focus&&
window.setTimeout(function(){$(d).focus()},300);b.keyDown&&I.registerListener(b.keyDown.keyCode?b.keyDown.keyCode:b.keyDown,b.keyDown.cb?b.keyDown.cb:b.fn)})},L=function(a){var c=a.script,b=e("div","viewer_last","install"),g=e("div","viewer_content","install_content"),d=e("div","ask_action_buttons","install_buttons");x(d,"install",[{label:a.messages.action,fn:J,focus:!0},{label:a.messages.flags.install?k.getMessage("Process_with_Chrome"):null,fn:function(){K(c.fileURL);$(b).hide()}},{label:k.getMessage("Cancel"),
fn:r,keyDown:27}]);g.appendChild(d);b.appendChild(g);return b},M=function(a){var c=e("div","viewer_last","import"),b=e("div","viewer_content","import_content"),g=e("div","ask_action_buttons","import_buttons");x(g,"import",[{label:k.getMessage("Import"),fn:function(){var b=Object.keys(a);p(f.aid,"import",{data:{import_ids:b}})},focus:!0},{label:k.getMessage("Cancel"),fn:r,keyDown:27}]);b.appendChild(g);c.appendChild(b);return c},N=function(a){a=e("div","viewer_last","ok");var c=e("div","viewer_content",
"ok_content"),b=e("div","ask_action_buttons","ok_buttons");x(b,"import",[{label:k.getMessage("Ok"),fn:r,focus:!0}]);c.appendChild(b);a.appendChild(c);return a},O=function(a,c){var b=e("div","viewer_last","ok"),g=e("div","viewer_content","ok_content"),d=e("div","ask_action_buttons","ok_buttons");x(d,"permission",[{label:k.getMessage("Ok"),fn:function(){chrome.permissions.request({permissions:[c.permission]},function(b){chrome.runtime&&chrome.runtime.lastError&&console.warn("notify: error on getting permission",
c.permission+"!","reason:",chrome.runtime.lastError.message);p(f.aid,"permission",{data:{granted:b,permission:c.permission}})})},focus:!0},{label:k.getMessage("Cancel"),fn:r,keyDown:27}]);g.appendChild(d);b.appendChild(g);var g=e("div","viewer_upper","permission"),d=e("div","viewer_info","general","permission"),h=e("div","viewer_content","general_content","permission"),n=m("h3","install","heading","permission"),D=e("span","message","heading","permission");n.textContent=c.title;D.textContent=c.message;
h.appendChild(D);d.appendChild(n);d.appendChild(h);g.appendChild(d);a.appendChild(g);a.appendChild(b)},A=function(a,c){var b=a.preparat,g=a.content,d=b.script||{},h=d.id;b.short_info||(b.short_info=[]);var n=e("div","viewer_upper",h),f=e("div","viewer_info","general",h),p=e("div","viewer_content","general_content",h),s=m("h3","install","heading",d.id);if(d.icon||d.icon64){var l=m("img","version","heading",h);l.src=d.icon||d.icon64;s.appendChild(l)}l=m("span","name","heading",h);l.textContent=b.heading||
d.name||"";s.appendChild(l);d.version&&(l=e("span","view_version","heading",h),l.textContent="v"==d.version[0]?"":"v",l.textContent+=d.version,s.appendChild(l));f.appendChild(s);c&&b.short_info.unshift({prop:"heading",value:b.messages.heading,label:k.getMessage("Action")});var r=e("table","script_desc",h);b.short_info.forEach(function(b){var a=d[b.prop]||b.value;if(a||!c){var g=e("tr","script_desc",b.prop,h),n=e("td","script_desc",b.prop,h+"dt"),f=e("td","script_desc",b.prop,h+"dd");n.textContent=
b.label?b.label:"";f.textContent=a||k.getMessage("_not_set_");g.appendChild(n);g.appendChild(f);r.appendChild(g)}});p.appendChild(r);var s=e("div","viewer_info","info",h),q;c?q=p:(q=e("div","viewer_content","info_content",h),l=m("h4","action","heading",h),l.textContent=b.messages.heading,q.appendChild(l));["errors","warnings","info"].forEach(function(a){var c=m("table",a,h);(b.messages[a]||[]).forEach(function(b){var d=m("tr",a,h),e=m("td",a,h+"dt"),g=m("td",a,h+"dd");"info"==a?(e.textContent=b.label,
g.textContent=b.value):"warnings"==a?(e.innerHTML='<img src="'+B.get("critical")+'"></img>&nbsp;',g.innerHTML=t.safeTagsReplace(b).replace(/\n/,"<br />")):"errors"==a&&(e.innerHTML='<img src="'+B.get("error")+'"></img>&nbsp;',g.innerHTML=t.safeTagsReplace(b).replace(/\n/,"<br />"));d.appendChild(e);d.appendChild(g);c.appendChild(d)});q.appendChild(c)});l=function(b,a,c,g){var n=m("table",b,h),f=0,l={};a.forEach(function(a){if(!(f>g||l[a])){l[a]=!0;var d=e("tr",b+"desc",a,h+f),k=e("td",b+"desc",a,
h+f+"dt"),m=e("td",b+"desc",a,h+f+"dd");k.innerHTML=0==f?t.safeTagsReplace(c.label):"&nbsp;";m.innerHTML=f==g?'<span title="'+t.safeTagsReplace(c.warning)+'">...!</span>':t.safeTagsReplace(a);d.appendChild(k);d.appendChild(m);n.appendChild(d);f++}});if(d.options&&(a=d.options.override&&d.options.override["use_"+b])&&a.length){a=e("tr",b+"desc","ovverride",h+f);var p=e("td",b+"desc","ovverride",h+f+"dt"),r=e("td",b+"desc","ovverride",h+f+"dd");p.innerHTML=0==f?t.safeTagsReplace(c.label):"&nbsp;";r.innerHTML=
t.safeTagsReplace(" ("+k.getMessage("overwritten_by_user")+")");a.appendChild(p);a.appendChild(r);n.appendChild(a)}q.appendChild(n)};l("includes",(d.includes||[]).concat(d.matches||[]),{label:k.getMessage("Include_s__"),warning:k.getMessage("Attention_Can_not_display_all_includes_")},5);l("excludes",d.excludes||[],{label:k.getMessage("Exclude_s__"),warning:k.getMessage("Attention_Can_not_display_all_excludes_")},3);f.appendChild(p);s.appendChild(q);n.appendChild(f);n.appendChild(s);g.appendChild(n);
a.install&&g.appendChild(a.install(b));a.editor&&g.appendChild(a.editor(b))},K=function(a){p(f.aid,"abort");window.setTimeout(function(){window.location=a+"#bypass=true"},10)},r=function(a,c){p(f.aid,"abort");window.setTimeout(function(){window.close()},100)},E=function(a,c){p(f.aid,"unload");v&&(window.clearInterval(v),v=null);window.removeEventListener("unload",E)};window.addEventListener("unload",E);var F=function(){window.location.search||window.location.hash?(f=q.getUrlArgs(),f.aid?(p(f.aid,
"preparat").done(function(a){a.i18n&&k.setLocale(a.i18n);C=k.getMessage("Install");var c=null;a.preparat&&("install"==a.type?c=function(){A({content:w(),preparat:a.preparat,install:L,editor:H})}:"install_error"==a.type?c=function(){A({content:w(),preparat:a.preparat,install:N},!0)}:"import"==a.type?c=function(){var b=w(),c=a.preparat;b.appendChild(M(c));for(var d in c){var h=c[d],f=e("div","viewer_upper",d);A({content:f,preparat:h},!0);b.appendChild(f)}}:"permission"==a.type&&(c=function(){O(w(),
a.preparat)}),v=window.setInterval(P,6E4),c&&window.setTimeout(c,1))}).fail(function(){r()}),u.wait(k.getMessage("Please_wait___"))):r()):window.onhashchange=function(){F()}},P=function(){return p(f.aid,"ping",{bg:!0})},J=function(){return p(f.aid,"install")},p=function(a,c,b){b=b||{};var e=y();try{var d={aid:a,method:c};b.data&&q.each(b.data,function(a,c){d[c]=b.data[c]});sendMessage({method:"askCom",data:d},function(a){b.bg||u.hide();a.error?("close"==a.action&&r(),e.reject(a)):e.resolve(a)});b.bg||
u.wait(k.getMessage("Please_wait___"))}catch(f){console.warn("sS: "+f.message),e.reject()}return e.promise()};chrome.extension.onMessage.addListener(function(a,c,b){if("confirm"==a.method)q.confirm(a.msg,function(a){b({confirm:a})});else if("showMsg"==a.method)q.alert(a.msg),b({});else return!1;return!0});F()})});
