/*
 Copyright (c) 2013 Gildas Lormeau. All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

 1. Redistributions of source code must retain the above copyright notice,
 this list of conditions and the following disclaimer.

 2. Redistributions in binary form must reproduce the above copyright
 notice, this list of conditions and the following disclaimer in
 the documentation and/or other materials provided with the distribution.

 3. The names of the authors may not be used to endorse or promote products
 derived from this software without specific prior written permission.

 THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED WARRANTIES,
 INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
 FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL JCRAFT,
 INC. OR ANY CONTRIBUTORS TO THIS SOFTWARE BE LIABLE FOR ANY DIRECT, INDIRECT,
 INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
 OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
(function(t){function B(){var b=-1,a=this;a.append=function(c){var d,h=a.table;for(d=0;d<c.length;d++)b=b>>>8^h[(b^c[d])&255]};a.get=function(){return~b}}function U(b,a,c){if(b.slice)return b.slice(a,a+c);if(b.webkitSlice)return b.webkitSlice(a,a+c);if(b.mozSlice)return b.mozSlice(a,a+c);if(b.msSlice)return b.msSlice(a,a+c)}function w(b,a){var c,d;c=new ArrayBuffer(b);d=new Uint8Array(c);a&&d.set(a,0);return{buffer:c,array:d,view:new DataView(c)}}function C(){}function D(b){var a=this,c;a.size=0;
a.init=function(d,h){var e=new Blob([b],{type:I});c=new v(e);c.init(function(){a.size=c.size;d()},h)};a.readUint8Array=function(b,a,e,f){c.readUint8Array(b,a,e,f)}}function E(b){var a=this,c;a.size=0;a.init=function(d){for(var h=b.length;"="==b.charAt(h-1);)h--;c=b.indexOf(",")+1;a.size=Math.floor(0.75*(h-c));d()};a.readUint8Array=function(a,h,e){var f=w(h),k=4*Math.floor(a/3),p=4*Math.ceil((a+h)/3),p=t.atob(b.substring(k+c,p+c));for(a=k=a-3*Math.floor(k/4);a<k+h;a++)f.array[a-k]=p.charCodeAt(a);
e(f.array)}}function v(b){this.size=0;this.init=function(a){this.size=b.size;a()};this.readUint8Array=function(a,c,d,h){var e=new FileReader;e.onload=function(a){d(new Uint8Array(a.target.result))};e.onerror=h;e.readAsArrayBuffer(U(b,a,c))}}function z(){}function F(b){var a;this.init=function(b){a=new Blob([],{type:I});b()};this.writeUint8Array=function(b,d){a=new Blob([a,J?b:b.buffer],{type:I});d()};this.getData=function(c,d){var h=new FileReader;h.onload=function(a){c(a.target.result)};h.onerror=
d;h.readAsText(a,b)}}function G(b){var a="",c="";this.init=function(c){a+="data:"+(b||"")+";base64,";c()};this.writeUint8Array=function(b,h){var e,f=c.length,k=c;c="";for(e=0;e<3*Math.floor((f+b.length)/3)-f;e++)k+=String.fromCharCode(b[e]);for(;e<b.length;e++)c+=String.fromCharCode(b[e]);2<k.length?a+=t.btoa(k):c=k;h()};this.getData=function(b){b(a+t.btoa(c))}}function H(b){var a;this.init=function(c){a=new Blob([],{type:b});c()};this.writeUint8Array=function(c,d){a=new Blob([a,J?c:c.buffer],{type:b});
d()};this.getData=function(b){b(a)}}function M(b,a,c,d,h,e,f,k,p,q){function n(a){a=a.data;var d=a.data;a.onappend&&(l+=d.length,c.writeUint8Array(d,function(){e(!1,d);g()},q));a.onflush&&(d?(l+=d.length,c.writeUint8Array(d,function(){e(!1,d);b.removeEventListener(A,n,!1);k(l)},q)):(b.removeEventListener(A,n,!1),k(l)));a.progress&&f&&f(m+a.current,h)}function g(){m=r*x;m<h?a.readUint8Array(d+m,Math.min(x,h-m),function(a){b.postMessage({append:!0,data:a});r++;f&&f(m,h);e(!0,a)},p):b.postMessage({flush:!0})}
var r=0,m,l;l=0;b.addEventListener(A,n,!1);g()}function N(b,a,c,d,h,e,f,k,p,q){function n(){var l;r=g*x;r<h?a.readUint8Array(d+r,Math.min(x,h-r),function(a){var k=b.append(a,function(){f&&f(d+r,h)});m+=k.length;e(!0,a);c.writeUint8Array(k,function(){e(!1,k);g++;setTimeout(n,1)},q);f&&f(r,h)},p):(l=b.flush())?(m+=l.length,c.writeUint8Array(l,function(){e(!1,l);k(m)},q)):k(m)}var g=0,r,m=0;n()}function V(b,a,c,d,h,e,f,k,p){function q(a,b){h&&!a&&r.append(b)}function n(a){e(a,r.get())}var g,r=new B;
t.zip.useWebWorkers?(g=new Worker(t.zip.workerScriptsPath+W),M(g,b,a,c,d,q,f,n,k,p)):N(new t.zip.Inflater,b,a,c,d,q,f,n,k,p);return g}function X(b,a,c,d,h,e,f){function k(a,b){a&&g.append(b)}function p(a){d(a,g.get())}function q(){n.removeEventListener(A,q,!1);M(n,b,a,0,b.size,k,h,p,e,f)}var n,g=new B;t.zip.useWebWorkers?(n=new Worker(t.zip.workerScriptsPath+Y),n.addEventListener(A,q,!1),n.postMessage({init:!0,level:c})):N(new t.zip.Deflater,b,a,0,b.size,k,h,p,e,f);return n}function O(b,a,c,d,h,e,
f,k,p){function q(){var r=n*x;r<d?b.readUint8Array(c+r,Math.min(x,d-r),function(b){h&&g.append(b);f&&f(r,d,b);a.writeUint8Array(b,function(){n++;q()},p)},k):e(d,g.get())}var n=0,g=new B;q()}function P(b){var a,c="",d,h="\u00c7\u00fc\u00e9\u00e2\u00e4\u00e0\u00e5\u00e7\u00ea\u00eb\u00e8\u00ef\u00ee\u00ec\u00c4\u00c5\u00c9\u00e6\u00c6\u00f4\u00f6\u00f2\u00fb\u00f9\u00ff\u00d6\u00dc\u00f8\u00a3\u00d8\u00d7\u0192\u00e1\u00ed\u00f3\u00fa\u00f1\u00d1\u00aa\u00ba\u00bf\u00ae\u00ac\u00bd\u00bc\u00a1\u00ab\u00bb___\u00a6\u00a6\u00c1\u00c2\u00c0\u00a9\u00a6\u00a6++\u00a2\u00a5++--+-+\u00e3\u00c3++--\u00a6-+\u00a4\u00f0\u00d0\u00ca\u00cb\u00c8i\u00cd\u00ce\u00cf++__\u00a6\u00cc_\u00d3\u00df\u00d4\u00d2\u00f5\u00d5\u00b5\u00fe\u00de\u00da\u00db\u00d9\u00fd\u00dd\u00af\u00b4\u00ad\u00b1_\u00be\u00b6\u00a7\u00f7\u00b8\u00b0\u00a8\u00b7\u00b9\u00b3\u00b2_ ".split("");
for(a=0;a<b.length;a++)d=b.charCodeAt(a)&255,c=127<d?c+h[d-128]:c+String.fromCharCode(d);return c}function Q(b){var a,c="";for(a=0;a<b.length;a++)c+=String.fromCharCode(b[a]);return c}function R(b,a,c,d,h){b.version=a.view.getUint16(c,!0);b.bitFlag=a.view.getUint16(c+2,!0);b.compressionMethod=a.view.getUint16(c+4,!0);b.lastModDateRaw=a.view.getUint32(c+6,!0);var e;a:{var f=b.lastModDateRaw,k=(f&4294901760)>>16,f=f&65535;try{e=new Date(1980+((k&65024)>>9),((k&480)>>5)-1,k&31,(f&63488)>>11,(f&2016)>>
5,2*(f&31),0);break a}catch(p){}e=void 0}b.lastModDate=e;if(1===(b.bitFlag&1))h(Z);else{if(d||8!=(b.bitFlag&8))b.crc32=a.view.getUint32(c+10,!0),b.compressedSize=a.view.getUint32(c+14,!0),b.uncompressedSize=a.view.getUint32(c+18,!0);4294967295===b.compressedSize||4294967295===b.uncompressedSize?h($):(b.filenameLength=a.view.getUint16(c+22,!0),b.extraFieldLength=a.view.getUint16(c+24,!0))}}function aa(b,a){function c(){}function d(c,e){b.readUint8Array(b.size-c,c,function(b){b=w(b.length,b).view;var k;
try{k=1347093766==b.getUint32(0)}catch(p){a(K);return}k?e(b):d(c+1,e)},function(){a(K)})}c.prototype.getData=function(c,d,f,k){function p(a,b){l&&l.terminate();l=null;a&&a(b)}function q(a){var b=w(4);b.view.setUint32(0,a);return m.crc32==b.view.getUint32(0)}function n(a,b){k&&!q(b)?g():c.getData(function(a){p(d,a)})}function g(){p(a,S)}function r(){p(a,ba)}var m=this,l;b.readUint8Array(m.offset,30,function(d){d=w(d.length,d);var e;1347093252!=d.view.getUint32(0)?a(L):(R(m,d,4,!1,a),e=m.offset+30+
m.filenameLength+m.extraFieldLength,c.init(function(){0===m.compressionMethod?O(b,c,e,m.compressedSize,k,n,f,g,r):l=V(b,c,e,m.compressedSize,k,n,f,g,r)},r))},g)};return{getEntries:function(h){22>b.size?a(L):d(22,function(d){var f,k;f=d.getUint32(16,!0);k=d.getUint16(8,!0);b.readUint8Array(f,b.size-f,function(b){var d=0,e=[],g,f,m=w(b.length,b);for(b=0;b<k;b++){g=new c;if(1347092738!=m.view.getUint32(d)){a(L);return}R(g,m,d+6,!0,a);g.commentLength=m.view.getUint16(d+32,!0);g.directory=16==(m.view.getUint8(d+
38)&16);g.offset=m.view.getUint32(d+42,!0);f=Q(m.array.subarray(d+46,d+46+g.filenameLength));g.filename=2048===(g.bitFlag&2048)?decodeURIComponent(escape(f)):P(f);g.directory||"/"!=g.filename.charAt(g.filename.length-1)||(g.directory=!0);f=Q(m.array.subarray(d+46+g.filenameLength+g.extraFieldLength,d+46+g.filenameLength+g.extraFieldLength+g.commentLength));g.comment=2048===(g.bitFlag&2048)?decodeURIComponent(escape(f)):P(f);e.push(g);d+=46+g.filenameLength+g.extraFieldLength+g.commentLength}h(e)},
function(){a(K)})})},close:function(a){a&&a()}}}function T(b){var a,c=[];for(a=0;a<b.length;a++)c.push(b.charCodeAt(a));return c}function ca(b,a,c){function d(a,b){f&&f.terminate();f=null;a&&a(b)}function h(){d(a,da)}function e(){d(a,S)}var f,k={},p=[],q=0;return{add:function(n,g,r,m,l){function s(a){var d;y=l.lastModDate||new Date;u=w(26);k[n]={headerArray:u.array,directory:l.directory,filename:v,offset:q,comment:T(unescape(encodeURIComponent(l.comment||"")))};u.view.setUint32(0,335546376);l.version&&
u.view.setUint8(0,l.version);c||0===l.level||l.directory||u.view.setUint16(4,2048);u.view.setUint16(6,(y.getHours()<<6|y.getMinutes())<<5|y.getSeconds()/2,!0);u.view.setUint16(8,(y.getFullYear()-1980<<4|y.getMonth()+1)<<5|y.getDate(),!0);u.view.setUint16(22,v.length,!0);d=w(30+v.length);d.view.setUint32(0,1347093252);d.array.set(u.array,4);d.array.set(v,30);q+=d.array.length;b.writeUint8Array(d.array,a,h)}function t(a,c){var f=w(16);q+=a||0;f.view.setUint32(0,1347094280);"undefined"!=typeof c&&(u.view.setUint32(10,
c,!0),f.view.setUint32(4,c,!0));g&&(f.view.setUint32(8,a,!0),u.view.setUint32(14,a,!0),f.view.setUint32(12,g.size,!0),u.view.setUint32(18,g.size,!0));b.writeUint8Array(f.array,function(){q+=16;d(r)},h)}function x(){l=l||{};n=n.trim();l.directory&&"/"!=n.charAt(n.length-1)&&(n+="/");k.hasOwnProperty(n)?a(ea):(v=T(unescape(encodeURIComponent(n))),p.push(n),s(function(){g?c||0===l.level?O(g,b,0,g.size,!0,t,m,e,h):f=X(g,b,l.level,t,m,e,h):t()},h))}var u,v,y;g?g.init(x,e):x()},close:function(a){var c,
f=0,e=0,l,s;for(l=0;l<p.length;l++)s=k[p[l]],f+=46+s.filename.length+s.comment.length;c=w(f+22);for(l=0;l<p.length;l++)s=k[p[l]],c.view.setUint32(e,1347092738),c.view.setUint16(e+4,5120),c.array.set(s.headerArray,e+6),c.view.setUint16(e+32,s.comment.length,!0),s.directory&&c.view.setUint8(e+38,16),c.view.setUint32(e+42,s.offset,!0),c.array.set(s.filename,e+46),c.array.set(s.comment,e+46+s.filename.length),e+=46+s.filename.length+s.comment.length;c.view.setUint32(e,1347093766);c.view.setUint16(e+8,
p.length,!0);c.view.setUint16(e+10,p.length,!0);c.view.setUint32(e+12,f,!0);c.view.setUint32(e+16,q,!0);b.writeUint8Array(c.array,function(){d(function(){b.getData(a)})},h)}}}var L="File format is not recognized.",Z="File contains encrypted entry.",$="File is using Zip64 (4gb+ file size).",K="Error while reading zip file.",da="Error while writing zip file.",ba="Error while writing file data.",S="Error while reading file data.",ea="File already exists.",x=524288,W="inflate.js",Y="deflate.js",I="text/plain",
A="message",J;try{J=0===(new Blob([new DataView(new ArrayBuffer(0))])).size}catch(fa){}B.prototype.table=function(){var b,a,c,d=[];for(b=0;256>b;b++){c=b;for(a=0;8>a;a++)c=c&1?c>>>1^3988292384:c>>>1;d[b]=c}return d}();D.prototype=new C;D.prototype.constructor=D;E.prototype=new C;E.prototype.constructor=E;v.prototype=new C;v.prototype.constructor=v;z.prototype.getData=function(b){b(this.data)};F.prototype=new z;F.prototype.constructor=F;G.prototype=new z;G.prototype.constructor=G;H.prototype=new z;
H.prototype.constructor=H;t.zip={Reader:C,Writer:z,BlobReader:v,Data64URIReader:E,TextReader:D,BlobWriter:H,Data64URIWriter:G,TextWriter:F,createReader:function(b,a,c){b.init(function(){a(aa(b,c))},c)},createWriter:function(b,a,c,d){b.init(function(){a(ca(b,c,d))},c)},workerScriptsPath:"",useWebWorkers:!0}})(this);
