Registry.registerRaw("emulation.js","52",function(){window.console||console||(console={log:function(a){tmCE.log((_background?"BG: ":"")+a)},warn:function(a){tmCE.log((_background?"BG: ":"")+a)},error:function(a){tmCE.log((_background?"BG: ":"")+a)}});Converter||(Converter={decode:function(a){return window.atob(a)},encode:function(a){return window.btoa(a)}});var k=function(a){return void 0===a?void 0:null==a?null:String(a)},c={key:"##REPLACE_KEY##",responses:{},clean:function(){c.responses=
null;c.extension.requestHandlers=null;c=c.tabs.updateListeners=null},runUpdateListeners:function(a,b,d){for(var e=0;e<c.tabs.updateListeners.length;e++){var f=c.tabs.updateListeners[e];try{f(a,b,d)}catch(g){console.log("emu: Error (runUpdateListeners):"+g+"\n"+f.toString())}}},runRequestHandlers:function(a,b,d,e){for(var f=0;f<c.extension.requestHandlers.length;f++){var g=c.extension.requestHandlers[f];try{g(a,b,function(a){tmCE.onResponse(c.key,e,d,JSON.stringify(a))})}catch(h){console.log("emu: Error (runRequestHandlers):"+
h+"\n"+g.toString())}}},runContentRequestHandlers:function(a,b,d,e){for(var f=0;f<c.extension.requestHandlers.length;f++){var g=c.extension.requestHandlers[f];try{g(a,b,function(a){tmCE.onContentResponse(c.key,e,d,JSON.stringify(a))})}catch(h){console.log("emu: Error (runContentRequestHandlers):"+h+"\n"+g.toString())}}},runRequest:function(a,b,d){try{var e=JSON.parse(Converter.decode(b));c.runRequestHandlers(e.request,e.sender,a,d)}catch(f){console.log("emu: Json parse error (runRequest):"+f+"\n"+
b)}},runContentRequest:function(a,b,d){try{var e=JSON.parse(Converter.decode(b));c.runContentRequestHandlers(e.request,e.sender,a,d)}catch(f){console.log("emu: Json parse error (runContentRequest):"+f+"\n"+b)}},runResponse:function(a,b){try{for(var d in c.responses)if(d==a){var e="";try{e=JSON.parse(Converter.decode(b)),c.responses[d](e)}catch(f){console.log("emu: Json parse error (runResponse):"+f+"\n"+b)}delete c.responses[d];return}}catch(g){console.log("emu: Json parse error (runResponse):"+g+
"\n"+b)}console.log("WARN: emu: responseId "+a+" not found!")},runConnectResponse:function(a,b){try{for(var d in c.responses)if(d==a){var e="",f=!1;try{e=JSON.parse(Converter.decode(b)),c.responses[d](e),f=e.onDisconnect}catch(g){console.log("emu: Json parse error (runConnectResponse):"+g+"\n"+b)}f&&(c.responses[d]=null);return}}catch(h){console.log("emu: Json parse error (runConnectResponse):"+h+"\n"+b)}console.log("WARN: emu: responseId "+a+" not found!")},getResponseId:function(a){var b=0;if(a){for(;0==
b||void 0!=c.responses[b];)b=((new Date).getTime()+Math.floor(19831206*Math.random()+1)).toString();c.responses[b]=a}return b},extension:{requestHandlers:[],getURL:function(a){return k(tmCE.getUrl(c.key,a))},connect:function(a){var b={oMlisteners:[],oDlisteners:[],notifyListeners:function(a,b){for(var c=0;c<a.length;c++)a[c](b)},postMessage:function(a){tmCE.sendExtensionPortMessage(c.key,JSON.stringify(a),d)},onMessage:{addListener:function(a){b.oMlisteners.push(a)}},onDisconnect:{addListener:function(a){b.oDlisteners.push(a)}},
disconnect:function(){b.oMlisteners=null;b=b.oDlisteners=null}},d=c.getResponseId(function(a){a.onMessage?b&&b.notifyListeners(b.oMlisteners,a.msg):a.onDisconnect&&b&&(b.notifyListeners(b.oDlisteners),b=null)});tmCE.sendExtensionConnect(c.key,JSON.stringify(a),d);return b},sendMessage:function(a,b){var d=c.getResponseId(b);tmCE.sendExtensionMessage(c.key,JSON.stringify(a),d)},onMessage:{addListener:function(a){c.extension.requestHandlers.push(a)}}},i18n:{getMessage:function(){for(var a=[],b=0;b<arguments.length;b++)a.push(arguments[b]);
a=tmCE.getMessage(c.key,JSON.stringify(a));return k(a)}},tabs:{updateListeners:[],sendMessage:function(a,b,d){d=c.getResponseId(d);tmCE.sendTabsRequest(c.key,a,JSON.stringify(b),d)},create:function(a){tmCE.createTab(c.key,JSON.stringify(a))},query:function(a,b){var d=c.getResponseId(b);tmCE.queryTab(c.key,JSON.stringify(a),d)},update:function(a,b){tmCE.updateTab(c.key,a,b)},onUpdated:{addListener:function(a){c.tabs.updateListeners.push(a)}}}};TMwin.chromeEmu||Object.defineProperties(TMwin,{chromeEmu:{value:c,
enumerable:!1,writable:!1,configurable:!1}})});
