Registry.registerRaw("environment.js","52",function(){TMwin.domContentLoaded=!1;TMwin.loadHappened=!1;TMwin.domNodeInserted=!1;TMwin.props={};TMwin.adjustLogLevel=function(a){void 0!==a&&(logLevel=a);D|=60<=logLevel};var p=function(){var a={objs:{},push:function(d,b){0!==b&&1!==b&&(b=0);var c=Math.floor(19831206*Math.random()+1);a.objs[c]={fn:d,prio:b};return c},remove:function(d){delete a.objs[d]},get:function(d){for(var b=[],c=0;1>=c;c++)for(var h in a.objs)a.objs.hasOwnProperty(h)&&
(a.objs[h].prio!==c||void 0!==d&&h!=d||b.push(a.objs[h].fn));return void 0===d?b:b[0]},finalize:function(d){if(void 0===d){d=a.get();for(var b=0;b<d.length;b++)d[b]()}else return a.objs[d]&&(b=a.objs[d].fn(),delete a.objs[d]),b}};return a}();TMwin.adjustLogLevel();var m=TMwin.chromeEmu,L=function(a){return{}.toString.apply(a).match(/\s([a-z|A-Z]+)/)[1]},B=function(a,d){void 0==d&&(d=100);return d&&a&&(a==document||B(a.parentNode,d-1))},Q=function(){var a=function(){};a.prototype={};return new a},
Y=function(){var a=Q(),d=function(a,c,b,d,g,e){var f=b[d];b[d]=e&&"string"===typeof f?new Function(f):function(){return f.apply(g,arguments)};return c.apply(a,b)},b={setTimeout:{enhance:function(){return d(window,window.setTimeout,arguments,0,a,!0)}},setInterval:{enhance:function(){return d(window,window.setInterval,arguments,0,a,!0)}},location:{get:!0,set:function(a){window.location.href=a}},clearInterval:{wrap:!0},clearTimeout:{wrap:!0},addEventListener:{enhance:function(){return d(window,window.addEventListener,
arguments,1,a,!0)}},removeEventListener:{enhance:function(){return d(window,window.removeEventListener,arguments,1,a,!0)}}},c=function(b){return b==window?a:b},h=function(a,b,c,d){c||(c=a);var g=function(){var g=a[b].apply(c,arguments);d&&(g=d(g));return g};g.__proto__=a[b];g.prototype=a[b].prototype;return g},e=function(b){var c,g,d=null,d=function(d){c=d;g=function(){return d.apply(a,arguments)};window[b]=g};a.__defineGetter__(b,function(){return void 0===c||g!==window[b]?window[b]:c});a.__defineSetter__(b,
d)},f=function(b,d,g){var e,f=null,k=null,f="function"===typeof d.get?d.get:function(){g&&g.get_cb&&g.get_cb.apply(this,arguments);return void 0===e?c(window[b]):e};"function"===typeof d.set?k=d.set:d.get||(k=function(a){g&&g.set_cb&&g.set_cb.apply(this,arguments);e=a});f&&a.__defineGetter__(b,f);k&&a.__defineSetter__(b,k)};(function(){var a=0,b=function(b){for(var c=a;c<b;c++)f(String(c),{get:!0});a=Math.max(b,a)};f("length",{},{get_cb:function(){b(window.frames.length)}});b(Math.max(window.frames.length,
7))})();for(var g in b)b.hasOwnProperty(g)&&(TMwin.windowProps[g]=TMwin.windowProps[g]||!1!==b[g]);var k;for(g in TMwin.windowProps)if(TMwin.windowProps.hasOwnProperty(g)&&!1!==b[g]){k={};try{try{b[g]?b[g].wrap?(k.wrap=!0,k.that=b[g].that):b[g].direct?k.direct=!0:b[g].enhance?k.enhance=b[g].enhance:b[g].get&&(k.get=b[g].get,k.set=b[g].set):"function"===typeof window[g]?TMwin.windowProps[g].proto?k.wrap=!0:k.direct=!0:"number"===typeof window[g]||"string"===typeof window[g]?k.get=!0:TMwin.windowProps[g].event&&
TMwin.windowProps[g].proto?k.event=!0:k.direct=!0}catch(s){k.get=!0}k.direct?a[g]=c(window[g]):k.enhance?a[g]=k.enhance:k.event?e(g):k.get||k.set?f(g,k):k.wrap&&function(){var b=g;a[b]=h(window,b,k.that,c)}()}catch(l){console.warn("env: error while creating a new sandbox: "+l.message)}}return a},Z=function(a,d,b,c,h){var e=null;try{var f=c.sandboxes[a.id];f.__TMbackref||(f.__TMbackref={});var g="",k='arguments.callee.__tmid = { id: "'+a.id+'", run_at: "'+a.options.run_at+'", ns: "'+a.namespace+'" };\n',
s=["context"],l=[void 0],p;for(p in c.elements[a.id])if(c.elements[a.id].hasOwnProperty(p)){var q=c.elements[a.id][p];q.name?q.overwrite?(s.push(q.name),l.push(q.value)):q.scriptid?(f.__TMbackref[q.name+"_"+q.scriptid]=q.value,s.push(q.name),l.push('context.__TMbackref["'+q.name+"_"+q.scriptid+'"]')):(f[q.name]=q.value,s.push(q.name),l.push("context."+q.name)):D&&console.warn("env: WARN: unexpected item in props elem: "+JSON.stringify(q))}c=[];c.push(k);c.push("with (context) {\n");c.push("(function(");
c.push(s.join(","));c.push(") {");c.push("try {\n");c.push(b);c.push(d);c.push("\n} catch (e) {    if (e.message && e.stack) {        console.error(\"ERROR: Execution of script '"+a.name+'\' failed! " + e.message);        console.log(e.stack.replace(/\\(eval at <anonymous> /g, "").replace(/<anonymous>:/g, "").replace(/chrome-extension:\\/\\/[\\w]{32}\\/content\\.js:\\d*:\\d*\\)*, /g, ""));    } else {        console.error(e);    }};\n');c.push("}).apply(context, [");c.push(l.join(","));c.push("]);");
c.push("}\n");e=c.join("");s=function(a,b){(new Function("context",e)).apply(b,[b])};h?h(s,[e,f]):s(e,f)}catch(v){h={maxerr:999,newcap:!0,es5:!0,sloppy:!0,browser:!0,white:!0,plusplus:!0,nomen:!0,"continue":!0,todo:!0,eqeq:!0,passfail:!1,unparam:!0,devel:!0};f=null;try{f=JSLINT}catch(M){}h=f?f(e,h):!0;f="";if(h)f=g+d;else{g=(k+g).split("\n").length+2;b=b.split("\n").length;var k="",C;for(C in JSLINT.errors)(f=JSLINT.errors[C])&&f.line>=g&&(s=f.line-g+1,k+=s>b?"script: ":"require: ",k+=f.reason.replace(/.$/,
"")+" on line: "+s+" at character: "+f.character+"\n");f="JSLINT output:\n"+k}D||h?(console.error("env: ERROR: Syntax error @ '"+a.name+"'!\n##########################\n"+f+"##########################\nERROR: "+v.message+"\n"),console.error(v.stack)):console.error("env: ERROR: Syntax error @ '"+a.name+"'!\n"+v.message+"\n",v.stack);window.setTimeout(function(){D&&m.extension.sendMessage({method:"copyToClipboard",data:{content:d,type:"test"},id:"42"},function(){});throw v;},1)}},w=[],l={events:[],
done:{},running:null},x=function(a,d,b,c){var h={attrChange:0,attrName:null,bubbles:!0,cancelBubble:!1,cancelable:!1,clipboardData:void 0,currentTarget:null,defaultPrevented:!1,eventPhase:0,newValue:null,prevValue:null,relatedNode:null,returnValue:!0,srcElement:null,target:null,timeStamp:(new Date).getTime()};b="string"===typeof b?new Function(b):b;var e=new Event,f;for(f in h)e[f]=h[f];for(f in d)e[f]=d[f];e.type=a;b.apply(c,[e])},E=function(a){TMwin.loadHappened=!0;TMwin.domContentLoaded=!0;D&&
console.log("env: DOMContentLoaded Event!");y()},F=function(a){!TMwin.domNodeInserted&&D&&console.log("env: first DOMNodeInserted Event!");TMwin.loadHappened=!0;TMwin.domNodeInserted=!0;l&&l.events.push({event:a,domContentLoaded:TMwin.domContentLoaded})},G=function(a){TMwin.loadHappened=!0;D&&console.log("env: load Event!")},H=function(){document.removeEventListener("DOMNodeInserted",F,!1);document.removeEventListener("DOMContentLoaded",E,!1);document.removeEventListener("load",G,!1);window.removeEventListener("unload",
H,!1);if(null!=p){for(var a=p.get(),d=0;d<a.length;d++)a[d]();p=null}m.clean&&m.clean()},y=function(){for(var a=w.length;0<w.length;){var d=w.shift();try{window.setTimeout(d.fn,1)}catch(b){console.log("ERROR: Execution (loadListener) of script env "+d.name+" failed!"+b.message)}}return a},I=function(a,d){if(document.body)window.setTimeout(function(){a()},1);else{var b=function(){document.removeEventListener("load",b,!1);document.removeEventListener("DOMNodeInserted",b,!1);document.removeEventListener("DOMContentLoaded",
b,!1);I(a,d)};document.addEventListener("load",b,!1);document.addEventListener("DOMNodeInserted",b,!1);document.addEventListener("DOMContentLoaded",b,!1)}},$=function(a,d,b){w.push({fn:function(){a()},name:b});TMwin.domContentLoaded?y():D&&console.log("env: schedule for later events!")},J=function(a,d){void 0===d&&(d=20);return 0==d?null:!a.__tmid&&a.caller?J(a.caller,d-1):a.__tmid},R=function(a){p.finalize(a)},O=function(a,d,b){var c=TM_context_id+"#"+a,h=null,h=p.push(function(){m.extension.sendMessage({method:"unRegisterMenuCmd",
name:a,id:c},function(a){})},1);m.extension.sendMessage({method:"registerMenuCmd",name:a,id:TM_context_id,menuId:c,accessKey:b},function(c){c.run&&null!==h&&void 0!==p.get(h)?(window.setTimeout(function(){d()},1),O(a,d,b)):null!==h&&(p.remove(h),h=null)});return h},S=function(a,d){var b=!1,c=null,h=m.extension.connect("openInTab_"+TM_context_id);a&&0==a.search(/^\/\//)&&(a=window.location.protocol+a);h.onMessage.addListener(function(a){a.tabId?b&&e():a.close&&(b=!0,c&&(c(),c=void 0))});h.onDisconnect.addListener(function(){h=
null});h.postMessage({method:"openInTab",details:{url:a,id:TM_context_id,options:d},id:TM_context_id});var e=function(){h&&h.postMessage({method:"closeTab",id:TM_context_id})},f={close:function(){b?D&&console.debug("env: attempt to close already closed tab!"):(b=!0,e())}};f.__defineGetter__("closed",function(){return b});f.__defineGetter__("onclose",function(){return c});f.__defineSetter__("onclose",function(a){c=a});return f},T=function(a,d){var b=!1,c="Object"===L(a)?a:{url:a,name:d};c.url&&"/"===
c.url[0]&&(c.url=window.location.origin+c.url);var h=c.context;delete c.context;var e=m.extension.connect("download_"+TM_context_id);e.postMessage({method:"download",details:c,id:TM_context_id});var f=function(a,c){c=c||{};a&&!b&&window.setTimeout(function(){a.apply(c,[c])},1)};e.onMessage.addListener(function(a){try{a.data&&h&&(a.data.context=h),a.success?c.onload&&(a.data.responseXML&&(a.data.responseXML=unescape(a.data.responseXML)),f(c.onload,a.data)):a.progress?c.onprogress&&f(c.onprogress,a.data):
a.timeout?c.ontimeout&&f(c.ontimeout,a.data):c.onerror&&f(c.onerror,a.data)}catch(b){console.log("env: Error: TM_download - ",b,c)}});return{abort:function(){b=!0}}},U=function(a){var d=!1;a.url&&"/"===a.url[0]&&(a.url=window.location.origin+a.url);var b=a.context;delete a.context;var c=function(){var a={};Object.getOwnPropertyNames(XMLHttpRequest.__proto__).forEach(function(b){a[b]=!0});var b=function(){};Object.getOwnPropertyNames(XMLHttpRequest).forEach(function(c){a[c]||(b[c]=XMLHttpRequest[c])});
return b}(),h=function(a,b){b=b||{};a&&!d&&window.setTimeout(function(){b.__proto__=c;a.apply(b,[b])},1)};if(a.responseType||"FormData"===L(a.data)){var e,f=new XMLHttpRequest;void 0===a.async&&(a.async=!0);f.open(a.method,a.url,a.async,a.user,a.password);if(a.headers)for(e in a.headers)f.setRequestHeader(e,a.headers[e]);a.overrideMimeType&&f.overrideMimeType(a.overrideMimeType);a.responseType&&(f.responseType=a.responseType);"abort error load progress readystatechange timeout".split(" ").forEach(function(c){f["on"+
c]=function(){var d="",e=a.url;if(2<f.readyState&&(d=f.getAllResponseHeaders(),4==f.readyState)){d&&(d=d.replace(/TM-finalURL\: .*[\r\n]{1,2}/,""));var l=f.getResponseHeader("TM-finalURL");l&&(e=l)}d={readyState:f.readyState,status:"",statusText:"",responseHeaders:d,finalUrl:e,context:b};4==f.readyState&&(f.responseType&&""!=f.responseType?d.response=f.response:(d.responseText=f.responseText,d.responseXML=f.responseXML),d.status=f.status,d.statusText=f.statusText);h(a["on"+c],d)}});f.send(a.data)}else e=
m.extension.connect("xhr_"+TM_context_id),e.postMessage({method:"xhr",details:a,id:TM_context_id}),e.onMessage.addListener(function(c){try{c.data&&b&&(c.data.context=b),c.success?a.onload&&(c.data.responseXML&&(c.data.responseXML=unescape(c.data.responseXML)),h(a.onload,c.data)):c.change?a.onreadystatechange&&h(a.onreadystatechange,c.data):c.progress?a.onprogress&&h(a.onprogress,c.data):c.timeout?a.ontimeout&&h(a.ontimeout,c.data):a.onerror&&h(a.onerror,c.data)}catch(d){console.log("env: Error: TM_xmlhttpRequest",
d,a)}});return{abort:function(){d=!0}}},V=function(a,d){m.extension.sendMessage({method:"installScript",url:a,id:TM_context_id},function(a){d&&d(a)})},aa=function(a,d){var b=[],c=a.storage,h=a.script.uuid,e=a.script,f=null;(function(){f=m.extension.connect("storageListener_"+TM_context_id);f.onMessage.addListener(function(a){if(a.storage)for(var b in a.storage.data)if(a.storage.data.hasOwnProperty(b)){var e=b,f=c.data[b];c.data[b]=a.storage.data[b];l(e,f,c.data[b],!0)}a.removed&&(c[a.removed]=d);
a.error&&console.log("env: Error: storage listener... :(")});f.postMessage({method:"addStorageListener",uuid:h,id:TM_context_id})})();var g=function(a){f.postMessage({method:"saveStorageKey",uuid:h,key:a,value:c.data[a],id:TM_context_id,ts:c.ts})},k=function(a,b,c){c===d&&(c=function(a){return a});var e=[],f=null;if(a&&a.length){var f={GM_info:!0},g;for(g in a)if(a.hasOwnProperty(g)){var h=a[g];f[h]=!0}}for(g in b)b.hasOwnProperty(g)&&(h=b[g],f&&!f[c(h.name)]||e.push(h));return e},l=function(a,c,
d,f){if(c!=d)for(var e in b)if(b.hasOwnProperty(e)){var g=b[e];if(g&&g.key==a&&g.cb)try{g.cb(a,M(c),M(d),f)}catch(h){D&&console.warn("env: value change listener of '"+a+"' failed with: "+h.message)}}},w=function(a,c){var d=0,e;for(e in b)b.hasOwnProperty(e)&&b[e].id>d&&(d=e.id);d++;b.push({id:d,key:a,cb:c});return d},t=function(a){for(var c in b)if(b.hasOwnProperty(c)&&b[c].id==a)return delete b[c],!0},q=function(a){var b=c.data[a];c.ts=(new Date).getTime();delete c.data[a];g(a);l(a,b,c.data[a],!1)},
v=function(){var a=[],b;for(b in c.data)c.data.hasOwnProperty(b)&&a.push(b);return a},M=function(a,b){var c=a[0];a=a.substring(1);switch(c){case "b":return"true"==a;case "n":return Number(a);case "o":try{return JSON.parse(a)}catch(d){console.log("env: parseValueFromStorage: "+d)}return b;default:return a}},C=function(a,b){var d=c.data[a];return d?M(d,b):b},x=function(a,b){var d=c.data[a],e=(typeof b)[0];switch(e){case "o":try{b=e+JSON.stringify(b)}catch(f){console.log(f);return}break;default:b=e+
b}c.ts=(new Date).getTime();c.data[a]=b;g(a);l(a,d,c.data[a],!1)},y=function(a){for(var b in e.resources){var c=e.resources[b];if(c.name==a)return c.resText}return null},B=function(a){for(var b in e.resources){var c=e.resources[b];if(c.name==a)return c.resURL}return null},E=function(a){window.console?window.console.log(a):console.log(a)},F=function(a){try{var b=document.createElement("style");b.textContent=a;(document.head||document.body||document.documentElement||document).appendChild(b)}catch(c){console.log("Error: env: adding style "+
c)}},G=function(b,c,e,f,g){var h,k=null;c||(c=a.script.name);if(g){var l=typeof g;"number"===l?h=g:"object"===l&&(k=g.onclose,h=g.timeout)}e==d&&(e=a.script.icon?a.script.icon:a.script.icon64);m.extension.sendMessage({method:"notification",delay:h,msg:b,image:e,title:c,id:TM_context_id},function(a){a.clicked&&f&&f();k&&k(!0===a.clicked)})},H=function(a,b,c){var d=typeof b,e="text",f="text/plain";"object"===d?(b.type&&(e=b.type),b.mimetype&&(f=b.mimetype)):"string"===d&&(e=b);m.extension.sendMessage({method:"copyToClipboard",
data:{content:a,type:e,mimetype:f},id:TM_context_id},function(a){c&&c()})},I=function(a){m.extension.sendMessage({method:"getTab",id:TM_context_id,uid:e.uuid},function(b){a&&a(b.data)})},N=function(a,b){m.extension.sendMessage({method:"setTab",id:TM_context_id,tab:a,uid:e.uuid},function(a){b&&b()})},J=function(a){m.extension.sendMessage({method:"getTabs",id:TM_context_id,uid:e.uuid},function(b){a&&a(b.data)})},n=function(a,b){var c=window,d="__u__"+Math.floor(19831206*Math.random()+1),e=d+"_",f=TM_do;
TMwin.use.safeContext&&(window!==unsafeWindow?c=unsafeWindow:f=function(a){(new Function(a))()});c[d]=a;c[e]=b;f=f('window["'+d+'"].apply(this, window["'+e+'"])');delete c[d];delete c[e];return f},r=[],z=null,u;for(u in e.grant)if(e.grant.hasOwnProperty(u)&&"none"===e.grant[u]){z=n;break}var A=e.namespace+"_"+!!z;TMwin.props[A]===d&&(TMwin.props[A]={sandboxes:{},elements:{}},p.push(function(){TMwin.props[A]=null}));if(!z&&("sandbox"===TMwin.use.proxy&&r.push({name:"window",value:"context",overwrite:!0}),
!TMwin.use.safeContext)){var P={window:window};for(u in P)P.hasOwnProperty(u)&&function(){var a=u.replace(/^(.)/g,function(a){return a.toUpperCase()});r.push({name:"unsafe"+a,value:P[u]})}()}r.push({name:"CDATA",value:function(a){this.src=a;this.toXMLString=this.toString=function(){return this.src}}});r.push({name:"uneval",value:function(a){try{return"\\$1 = "+JSON.stringify(a)+";"}catch(b){console.log(b)}}});"sandbox"!==TMwin.use.proxy&&(r.push({name:"console",value:console}),r.push({name:"JSON",
value:JSON}),r.push({name:"top",value:"window.unsafeTop",overwrite:!0}),r.push({name:"location",value:window.location}),r.push({name:"document",value:window.document}));r.push({name:"undefined",value:d});r.push({name:"define",value:d});r.push({name:"module",value:d});n=[];n.push({name:"TM_addStyle",value:F});n.push({name:"TM_deleteValue",value:q});n.push({name:"TM_listValues",value:v});n.push({name:"TM_getValue",value:C});n.push({name:"TM_log",value:E});n.push({name:"TM_registerMenuCommand",value:O});
n.push({name:"TM_unregisterMenuCommand",value:R});n.push({name:"TM_openInTab",value:S});n.push({name:"TM_setValue",value:x});n.push({name:"TM_addValueChangeListener",value:w});n.push({name:"TM_removeValueChangeListener",value:t});n.push({name:"TM_xmlhttpRequest",value:U});n.push({name:"TM_download",value:T});n.push({name:"TM_setClipboard",value:H});n.push({name:"TM_getTab",value:I});n.push({name:"TM_setTab",value:N});n.push({name:"TM_saveTab",value:N});n.push({name:"TM_getTabs",value:J});n.push({name:"TM_installScript",
value:V});n.push({name:"TM_notification",value:G});n.push({name:"TM_getResourceText",value:y,scriptid:e.id});n.push({name:"TM_getResourceURL",value:B,scriptid:e.id});var K=[],W=new function(){this.GM_addStyle=function(a){return F(a)};this.GM_deleteValue=function(a){return q(a)};this.GM_listValues=function(){return v()};this.GM_getValue=function(a,b){return C(a,b)};this.GM_addValueChangeListener=function(a,b){return w(a,b)};this.GM_removeValueChangeListener=function(a){return t(a)};this.GM_log=function(a){return E(a)};
this.GM_registerMenuCommand=function(a,b,c){return O(a,b,c)};this.GM_unregisterMenuCommand=function(a){return R(a)};this.GM_openInTab=function(a,b){return S(a,b)};this.GM_setValue=function(a,b){return x(a,b)};this.GM_xmlhttpRequest=function(a){return U(a)};this.GM_download=function(a){return T(a)};this.GM_getResourceText=function(a){return y(a)};this.GM_getResourceURL=function(a){return B(a)};this.GM_notification=function(a,b,c,d,e){return G(a,b,c,d,e)};this.GM_installScript=function(a,b){return V(a,
b)};this.GM_getTab=function(a){return I(a)};this.GM_setTab=function(a,b){return N(a,b)};this.GM_saveTab=function(a){return N(a)};this.GM_getTabs=function(a){return J(a)};this.GM_setClipboard=function(a,b,c){return H(a,b,c)};Object.defineProperties(this,{GM_info:{get:function(){var b={observers:1,id:1,enabled:1,hash:1,fileURL:1},c={script:{}},d;for(d in e)e.hasOwnProperty(d)&&!b[d]&&(c.script[d]=e[d]);b=e.options.updateURL||e.options.fileURL;c.script["run-at"]=e.options.override.run_at||e.options.run_at;
c.script.excludes=e.options.override.orig_excludes;c.script.includes=e.options.override.orig_includes;c.script.matches=e.options.override.orig_includes;c.script.grant=e.grant;c.script.unwrap=!1;c.scriptMetaStr=a.header;c.scriptSource=a.code;c.scriptWillUpdate=!!b;c.scriptUpdateURL=b;c.version=a.version;c.scriptHandler="Tampermonkey";c.isIncognito=TMwin.isIncognito;return c},enumerable:!0,configurable:!0}})},X=[];for(u in W)X.push({name:u,value:W[u]});K=K.concat(k(e.grant,n,function(a){return a.replace(/^TM_/,
"GM_")}));K=K.concat(k(e.grant,X));r=r.concat(K);e.options.compat_prototypes&&(D&&console.log("env: option: add toSource"),Object.prototype.toSource||Object.defineProperties(Object.prototype,{toSource:{value:function(){var a=L(this);if("String"===a)return"(String('"+this.replace(/\'/g,"\\'")+"'))";if("Number"===a)return"(Number('"+Number(this)+"'))";if("Array"===a){for(var b="(new Array(",c=0;c<this.length;c++)a=L(this[c]),b="Null"===a?b+"null":"Undefined"===a?b+"undefined":b+this[c].toSource(),c+
1<this.length&&(b+=",");return b+"))"}return"JSON.parse(unescape('"+escape(JSON.stringify(this))+"'))"},enumerable:!1,writable:!0,configurable:!0}}),D&&console.log("env: option: add some array generics"),"indexOf lastIndexOf filter forEach every map some slice".split(" ").forEach(function(a){if("function"!==typeof Array[a]){var b={};b[a]={value:function(b){return Array.prototype[a].apply(b,Array.prototype.slice.call(arguments,1))},enumerable:!1,writable:!0,configurable:!0};Object.defineProperties(Array,
b)}}));TMwin.props[A].sandboxes[a.script.id]="sandbox"!==TMwin.use.proxy||z?Q():Y();TMwin.props[A].elements[a.script.id]=r;D&&console.debug("env: execute script "+e.name+" @ the "+(z?"un":TMwin.use.safeContext?"":"pseudo-")+"safe context now!");Z(e,a.code,a.requires,TMwin.props[A],z);p.push(function(){f.postMessage({method:"removeStorageListener",uuid:h,storage:c,id:TM_context_id});try{f.disconnect(),f=null}catch(d){}a=b=null})};m.extension.onMessage.addListener(function(a,d,b){if(a.id&&a.id!=TM_context_id)console.warn("env: Not for me! "+
TM_context_id+"!="+a.id);else if(d=window.self==window.top,"executeScript"==a.method)d=function(){aa(a);b({})},"document-start"==a.script.options.run_at?(D&&console.debug("env: run '"+a.script.name+"' ASAP -> document-start"),d()):"document-body"==a.script.options.run_at?(D&&console.debug("env: schedule '"+a.script.name+"' for document-body"),I(d,a.script.id)):(D&&console.debug("env: schedule '"+a.script.name+"' for document-end"),$(d,a.script.id,a.script.name));else if("onLoad"==a.method){TMwin.domContentLoaded=
!0;y();b({});var c=null,h=function(){l=c=null};p.push(function(){c&&window.clearTimeout(c);h()});c=window.setTimeout(h,2E3)}else d&&("loadUrl"==a.method?(window.location=a.url,b({})):"reload"==a.method?(window.location.reload(),b({})):"confirm"==a.method?window.setTimeout(function(){var c=confirm(a.msg);b({confirm:c})},100):"showMsg"==a.method?window.setTimeout(function(){window.setTimeout(function(){alert(a.msg)},1);b({})},100):console.log("env: unknown method "+a.method))});(function(){window.HTMLDocument.prototype.__evaluate||
(window.HTMLDocument.prototype.__evaluate=window.HTMLDocument.prototype.evaluate,window.HTMLDocument.prototype.evaluate=function(a,d,b,c,h){d||(d=this);var e;if("undefined"!=typeof XPathResult){try{e=this.__evaluate(a,d,b,c,h)}catch(f){}var g=!0;try{g&=!e.snapshotLength}catch(k){}try{g&=!e.singleNodeValue}catch(l){}g&&"."!=a.charAt(0)&&!B(d)&&(a=("/"==a.charAt(0)?".":"./")+a,e=this.__evaluate(a,d,b,c,h))}else e=d.selectNodes(a);return e},p.push(function(){window.HTMLDocument.prototype.evaluate=window.HTMLDocument.prototype.__evaluate}))})();
(function(){for(var a=[window.HTMLDocument.prototype,window.__proto__],d=[],b=0;b<a.length;b++)(function(){var c=a[b];c.__addEventListener||(c.__addEventListener=c.addEventListener,c.__removeEventListener=c.removeEventListener,c.removeEventListener=function(a,b,c){"DOMNodeInserted"==a&&l&&l.running==b&&(l.running=null);this.__removeEventListener(a,b,c)},c.addEventListener=function(a,b,c){var g=!0;if("load"==a||"DOMContentLoaded"==a||"DOMNodeInserted"==a){var k=null,p=this;try{k=J(arguments.callee)}catch(m){D&&
console.error("env: Error: event "+a,m)}if(k){var t=null;"load"==a?TMwin.loadHappened&&(t=function(){x("load",{attrName:"null",newValue:"null",prevValue:"null",eventPhase:window.Event.AT_TARGET,attrChange:MutationEvent.ADDITION,target:document,relatedNode:document,srcElement:document},b,p)},g=!1,d.push(t)):"DOMContentLoaded"==a?TMwin.domContentLoaded&&(t=function(){x("DOMContentLoaded",{attrName:"null",newValue:"null",prevValue:"null",eventPhase:window.Event.AT_TARGET,attrChange:MutationEvent.ADDITION,
target:document,relatedNode:document,srcElement:document},b,p)},g=!1,d.splice(0,0,t)):"DOMNodeInserted"==a&&l&&!l.done[k]&&(l.done[k]=!0,t=function(){var d="document-start"!=k.run_at&&"document-body"!=k.run_at;l.running=b;a:if(l)for(var g=l.events.length,m=0;m<g;m++)if(d&&!l.events[m].domContentLoaded||x("DOMNodeInserted",{attrName:"",newValue:"",prevValue:"",eventPhase:window.Event.AT_TARGET,target:l.events[m].event.target,relatedNode:l.events[m].event.relatedNode,srcElement:l.events[m].event.srcElement},
b,p),!l.running)break a;l.running&&p.__addEventListener(a,b,c);l.running=null},d.push(t));t&&(window.setTimeout(function(){if(d.length){var a=d[0];d=d.slice(1);a()}},1),g=!1)}}g&&this.__addEventListener(a,b,c)},p.push(function(){c.removeEventListener=c.__removeEventListener;c.addEventListener=c.__addEventListener}))})();TMwin.windowProps.__addEventListener={proto:!0};TMwin.windowProps.__removeEventListener={proto:!0}})();(function(){TMwin.use.safeContext&&!Object.getOwnPropertyDescriptor(window,"content")&&
Object.defineProperties(window,{content:{get:function(){return window.top},enumerable:!0,configurable:!1}})})();(function(){TMwin.use.safeContext&&(window.open=function(a){var d="__o__"+TM_context_id;a="window."+d+' = window.open(decodeURI("'+encodeURI(a)+'"));';TM_do(a);a=unsafeWindow[d];delete unsafeWindow[d];return a},p.push(function(){window.open=null}))})();(function(){if(TMwin.use.safeContext){var a=window.setTimeout,d=window.setInterval;window.setTimeout=function(){var b=arguments,c=b[0];"string"===
typeof c&&(b[0]=function(){TM_do(c)});return a.apply(this,b)};window.setInterval=function(){var a=arguments,c=a[0];"string"===typeof c&&(a[0]=function(){TM_do(c)});return d.apply(this,a)};p.push(function(){window.setTimeout=window.__setTimeout;window.setInterval=window.__setInterval})}})();document.addEventListener("DOMNodeInserted",F,!1);document.addEventListener("DOMContentLoaded",E,!1);document.addEventListener("load",G,!1);window.addEventListener("unload",H,!1);D&&console.debug("env: initialized (content, id:"+
TM_context_id+", "+window.location.origin+window.location.pathname+") ")});
