Registry.require(["helper","xmlhttprequest"],function(){var I=Registry.get("helper"),x=Registry.get("xmlhttprequest").run,f=$.Deferred,J=function(a){var b=f();b.resolve(a);return b.promise()},u=!1,y=null,g=0,v=null,l={ePASTEBIN:1,eCHROMESYNC:2},p={},q=[],r=!1,n=null,z=[{method:"HEAD",url:"http://www.google.com",extract:function(a,b){try{var c=b?b.split("\n"):null,d;for(d in c){var e=c[d].split(":"),f=e.shift()||"",h=e.join(":")||"";if("date"==f.trim().toLowerCase()&&h){var s=new Date(h);if(s)return s.getTime()-
(new Date).getTime()}}}catch(k){}return null}},{method:"GET",url:"http://json-time.appspot.com/time.json",extract:function(a,b){try{var c=JSON.parse(a);if(!c.error&&c.datetime){var d=new Date(c.datetime);if(d)return d.getTime()-(new Date).getTime()}}catch(e){}return null}}];p[l.ePASTEBIN]="http://pastebin.com/raw.php?i=%s";p[l.eCHROMESYNC]="";var A=function(){return(new Date).getTime()+n},B=function(){var a=f(),b=0,c=function(){if(b<z.length){var d=z[b];x({method:d.method,url:d.url},{ondone:function(e){4==
e.readyState&&(200==e.status?(e=d.extract(e.responseText,e.responseHeaders),null===e?(b++,window.setTimeout(c,1)):(n=e,a.resolve(!0))):(b++,window.setTimeout(c,1)))}})}else n=0,console.log("si: time offset detection failed!"),a.resolve(!1)};c();return a.promise()},D=function(){if(!u)try{chrome.storage.onChanged.addListener(C),u=!0}catch(a){}},C=function(a,b){if(g==l.eCHROMESYNC&&"sync"==b)if(null===n)B().done(function(){C(a,b)});else{var c=/@us$/,d;for(d in a){var e=a[d];if(-1!=d.search(c))for(var f=
0;f<q.length;f++)if(!k[d]){var h=w(e.newValue);if(h)q[f](d,h)}}}},K=function(a){var b=f(),c=[];try{a=a.replace(/\t/g,"    ");a=a.replace(/\r/g,"\n");a=a.replace(/\n\n+/g,"\n");for(var d=a.split("\n"),e=0;e<d.length;e++){var k=d[e],h=k.split("|");if(3<h.length)console.log("si: can't handle line: "+k);else{var s=h[h.length-1],l=null,m=null;if(1<h.length)for(var g=h.length-2;0<=g;g--)try{l=JSON.parse(h[g])}catch(n){m=h[g]}c.push({name:m,url:s,options:l||{}})}}}catch(p){console.warn("si: unable to parse data: "+
a)}b.resolve(c);return b.promise()},L=function(){var a=f();v?x({method:"GET",retries:3,url:v},{onload:function(b){4==b.readyState&&(200==b.status?K(b.responseText).done(function(b){a.resolve(b)}):a.reject())},onerror:a.reject}):a.reject({});return a.promise()},w=function(a,b){var c=null;try{c=JSON.parse(a)}catch(d){}return c&&c.url?c:null},t=function(a,b){var c=f();void 0===b&&(b=3);var d=function(){if(r)window.setTimeout(d,500);else{r=!0;try{a.apply(this,arguments).done(function(){r=!1;c.resolve.apply(this,
arguments)}).fail(function(){0<--b?window.setTimeout(d,500):(console.log("si: no retries left, wait for",6E4,"ms"),window.setTimeout(d,6E4))})}catch(e){console.warn(e),r=!1,c.reject(e)}}};d();return c.promise()},M=function(a){var b=f(),c=[];a?E().done(function(d){a=a.split("#")[0];c=I.select(d,function(b){return b.item&&b.item.url==a});b.resolve(c)}).fail(function(a){b.reject(a)}):b.resolve(c);return b.promise()},N=function(){var a=f();E().done(function(b){var c=/@us$/,d=[];b.forEach(function(a){var b=
a.key;a=a.item;var f=b.replace(c,""),g=null;(g=k[b]?w(k[b],b):a)&&d.push({id:f,url:g.url,options:g.options?g.options:{}})});a.resolve(d)}).fail(function(b){a.reject(b)});return a.promise()},E=function(){return t(function(){var a=f(),b=/@us$/;chrome.storage.sync.get(null,function(c){var d=[],e;for(e in c)-1!=e.search(b)&&d.push({key:e,item:w(c[e])});a.resolve(d)});return a.promise()})},F=function(a){return M(a).done(function(a){if(1<a.length){var c=f(),d=[];a.forEach(function(a){d.push(O(a.key))});
$.when.apply($,d).done(function(){c.resolve(a)});return c.promise()}return J(a)})},m=null,k={},O=function(a,b){return t(function(){var b=f();chrome.storage.sync.remove(a,function(a){(a=chrome.runtime?chrome.runtime.lastError:a)?b.reject(a):b.resolve()});return b.promise()})},G=function(a){return t(function(){var a=f();chrome.storage.sync.set(k,function(c){(c=chrome.runtime?chrome.runtime.lastError:c)?a.reject(c):(k={},a.resolve())});return a.promise()})},H=function(){var a=f();null===n?B().done(function(){H().done(a.resolve)}):
g==l.eCHROMESYNC?N().done(a.resolve).fail(function(b){a.reject(b)}):L().done(a.resolve).fail(function(b){a.reject(b)});return a.promise()};Registry.register("syncinfo","52",{init:function(a,b){q=[];var c=!1;y=b;g=a;a==l.eCHROMESYNC?(D(),c=!0):p[g]&&y&&(v=p[g].replace("%s",b),c=!0);return c},list:H,add:function(a){var b=f(),c={url:a.url,options:a.options};F(a.url).done(function(d){k[(d.length?d[0].key:null)||a.uuid+"@us"]=JSON.stringify(c);m&&window.clearTimeout(m);m=window.setTimeout(G,
3E3);b.resolve()});return b.promise()},reset:function(){return t(function(){var a=f();chrome.storage.sync.clear(function(){k={};a.resolve()});return a.promise()})},getTime:A,remove:function(a){var b=f(),c={url:a.url,options:a.options||{}};c.options.removed=A();F(a.url).then(function(d){k[(d.length?d[0].key:null)||a.uuid+"@us"]=JSON.stringify(c);m&&window.clearTimeout(m);m=window.setTimeout(G,3E3);b.resolve()});return b.promise()},debug:function(a){},addChangeListener:function(a){q.push(a);u||D()},
types:l})});
